- Makefile
- config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
- config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
- config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/role_binding.yaml
- config/webhook/kustomization.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
- go.mod
- hack/provision-test-env.sh
- Restore kustomize manifests to deploy operator
- Restore make targets to deploy
https://github.com/kyma-project/kyma/issues/16909
> Restore support to deploy operator with kustomize manifests

- controller/logparser/suite_test.go
- controller/logpipeline/suite_test.go
- controller/tracepipeline/suite_test.go
- webhook/logpipeline/webhook_suite_test.go
To avoid approval requests from macOS' firewall.
- Bind services to localhost in tests
> Bind services to localhost in tests

- go.mod
- internal/reconciler/metricpipeline/config_builder_test.go
- internal/reconciler/tracepipeline/config_builder_test.go
- The `gopkg.in/yaml.v2` dependency is used in the otelcollector config builder tests of the trace and metric pipeline to verify if the created config by the package is valid.
- The actual otel config however is created with `gopkg.in/yaml.v3`.
- This PR replaces the `v2` dependecy in the tests with the `v3`. As a result, the v2 is not explicitly required in the go.mod file
> remove gopkg.in/yaml.v2 dependency

- config/rbac/role.yaml
- main.go
- Create new cache which filters resources only from the given namespace. In order to restrict the RBAC for telemetry 
manager. 
- The cache contains resources that are filtered by namespace. Additionally secret resource is not namespace restricted. As we would like read secrets from different namespaces.
https://github.com/kyma-project/kyma/issues/17001
> Restrict RBAC for telemetry manager

- config/samples/http-mockserver.yaml
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/output.go
- internal/fluentbit/config/builder/output_test.go
- webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Fluent Bit's default settings make only one retry attempt on a retry-able output error. With our persistent buffer usage, more retries would be beneficial.
- Set retry_limit to no_limits for Fluent Bit http output
- Do not collect logs from http-mockserver sample
https://github.com/kyma-project/kyma/issues/17113
> Set unlimited retries for Fluent Bit http output

- Makefile
- config/samples/http-mockserver.yaml
- controller/tracepipeline/controller_test.go
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/output.go
- internal/fluentbit/config/builder/output_test.go
- internal/kubernetes/utils.go
- webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
- webhook/logpipeline/validation/variable_validator.go
- webhook/logpipeline/webhook_suite_test.go
Include kyma-project/telemetry-manager#94 to increase Fluent Bit retry limit.
- Set retry_limit to no_limits for Fluent Bit http output
- Do not collect logs from http-mockserver sample
- Add dummy e2e-test make target to make prow happy
- Fix linting errors
> Set unlimited retries for Fluent Bit http output (#94)

- controllers/telemetry/logparser_controller.go
- controllers/telemetry/logpipeline_controller.go
- internal/setup/predicates.go
- We should react if the fluent bit daemonset is deleted. Trigger a reconciler event in case of Fluent bit daemonset deletion so that it could be brought back
- Also logparser should not watch fluent bit daemonset as logpipeline is our main reconciler and this should be responsible for handling the fluent bit daemonset
> Watch fluentbit daemonset for deletion as well

- README.md
- config/manager/manager.yaml
- config/rbac/role.yaml
- config/samples/telemetry_v1alpha1_tracepipeline_jaeger.yaml
- config/webhook/manifests.yaml
- controllers/telemetry/metricpipeline_controller_test.go
- controllers/telemetry/suite_test.go
- controllers/telemetry/tracepipeline_controller_test.go
- internal/kubernetes/configmap_test.go
- internal/kubernetes/daemonset_test.go
- internal/kubernetes/deployment_test.go
- internal/reconciler/logpipeline/sync_test.go
- internal/resources/common/resources_test.go
- internal/resources/fluentbit/resources_test.go
- internal/resources/otelcollector/resources_test.go
- internal/setup/webhook_test.go
- main.go
- inject namespace of the manager via comman arg
- refactored tests to use a dummy namespace
- changed rbac files to use dummy system namespace which gets overriden by kusomization
https://github.com/kyma-project/kyma/issues/17195
> have manager namespace-agnostic

- controllers/telemetry/metricpipeline_controller.go
- controllers/telemetry/tracepipeline_controller.go
- internal/kubernetes/utils.go
- internal/kubernetes/utils_test.go
- Merge owner references when updating Kubernetes resources
- Replace `Ownes` by `Watches` during controller setup to reconcile also owners without controller flag
https://github.com/kyma-project/kyma/issues/17232
> Prepare owner references to support multiple pipelines

- Makefile
- internal/kubernetes/lock.go
- internal/kubernetes/lock_test.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/tracepipeline/reconciler.go
- internal/resources/otelcollector/resources.go
- main.go
Enhance pipeline lock mechanism to support limiting the number of TracePipelines and MetricPipelines to a number that is larger than one. The enhanced lock implementation uses the owner list to identify the current lock holders.
- Support limiting the pipeline count to a number larger than 1
https://github.com/kyma-project/kyma/issues/17223
> Enhance pipeline lock mechanism

- controllers/telemetry/logpipeline_controller_test.go
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/output.go
- internal/fluentbit/config/builder/output_test.go
PR #94 set the retry limit for the Fluent Bit HTTP output to unlimited to properly utilize the file system storage. Since the custom output also enforces a file system storage configuration, this PR adds the same retry behaviour to a custom output.
- Enable unlimited retries in LogPipelines with custom output
https://github.com/kyma-project/kyma/issues/17113
> Enable unlimited retries in LogPipelines with custom output

- Makefile
- config/manager/kustomization.yaml
- controllers/telemetry/otel_test_helpers.go
- internal/otelcollector/config/builder/config_builder.go
- internal/otelcollector/config/builder/config_builder_test.go
- internal/otelcollector/config/config.go
- internal/reconciler/metricpipeline/config_builder.go
- internal/reconciler/metricpipeline/config_builder_test.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/tracepipeline/config_builder.go
- internal/reconciler/tracepipeline/config_builder_test.go
- internal/reconciler/tracepipeline/reconciler.go
Add the pipeline name as an alias with the / notation to otlp, otlphttp, and logging exporters as a preparation to support multiple trace and metric pipelines.
- Add aliases to otel exporters
https://github.com/kyma-project/kyma/issues/17234
> Add aliases to otel exporters

- README.md
- config/manager/manager.yaml
- hack/provision-test-env.sh
- Including `kyma-system` in Kustomize files results in the lifecycle-manager deleting the `kyma-system` namespace when disabling the telemetry module which is an undesired action. Therefore, `kyma-system` namespace is removed from Kustomize files in this PR. When Kyma is deployed, the `kyma-system` namespace will already be created by the lifecycle-manager.
- Manually create the `kyma-system` namespace in the `provision-test-env.sh` script which is used in the e2e-test. This is needed as in the e2e-test we deploy the operator as standalone without the lifecycle-manager.
- Update README to manually create `kyma-system` namespace for deploying the operator as standalone without the lifecycle-manager.
> Remove kyma-system namespace from Kustomize files

- Makefile
- test/e2e/metrics_test.go
- test/e2e/testkit/mocks/backend_deployment.go
- test/e2e/testkit/otlp/matchers/metric_matchers.go
- test/e2e/testkit/otlp/matchers/metric_matchers_test.go
- test/e2e/testkit/otlp/matchers/trace_matchers.go
- test/e2e/testkit/otlp/matchers/trace_matchers_test.go
- test/e2e/tracing_test.go
Add end-to-end tests for support of multiple TracePipelines and MetricPipeliens. The added tests validate that the pipeline limit is enforced and reflected in the pending / running state, traces and metrics reach the backend from all pipelines, and a broken pipeline does not affect another one.
- Add E2E tests for multi-pipeline support
https://github.com/kyma-project/kyma/issues/17234
> Add E2E tests for multi-pipeline support

- test/e2e/metrics_test.go
- test/e2e/testkit/k8s/verifiers/deployment.go
- test/e2e/testkit/mocks/backend_deployment.go
- test/e2e/tracing_test.go
- We are using otel and nginx images from docker. These images are pull in unauthenticated docker pull which has rate limiting. To mitigate use images from kyma's docker registry
- Make sure the trace/metric backend is running before testing for traces.
- Some refactoring
> Reduce flakiness of e2e tests

- config/default/kustomization.yaml
- Change the value of `control-plane` label from `operator` to `telemetry-operator` which is the value currently used in the helm chart. This is needed to allow running the fast-integration test after a migration scenario from old Kyma to modular Kyma, since the test expects the label `control-plane=telemetry-operator` https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/telemetry-test/suite.js#L121
> Update `control-plane` label

- config/manager/manager.yaml
-Telemetry operator is watching many resources in the cluster like secrets, configmaps etc. It can happen that when in a cluster there are many of these resources it would cause the cache to be big. Current limit 256 Mi would not be enough in such cases so increase it to 384Mi
> increase memory limit for operator

- config/samples/telemetry_v1alpha1_logpipeline.yaml
- controllers/telemetry/logparser_controller.go
- controllers/telemetry/logpipeline_controller_test.go
- internal/reconciler/logparser/sync.go
- internal/reconciler/logparser/sync_test.go
- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/logpipeline/sync.go
- internal/reconciler/logpipeline/sync_test.go
- internal/resources/fluentbit/resources.go
- internal/resources/fluentbit/resources_test.go
- main.go
- Include static Fluent Bit configuration into checksum calculation
- Add owner references to all created resources
- Remove unnecessary checks for changed resources
- Add missing watch to LogParser controller
Preparations to fix https://github.com/kyma-project/kyma/issues/17611
> Improve fluent bit config reconciliation

- internal/resources/fluentbit/resources.go
- Exclude only telemetry-fluent-bit DaemonSet from kyma-system namespace
https://github.com/kyma-project/kyma/issues/17611
> Make excluded Fluent Bit container more specific

- test/e2e/metrics_test.go
- test/e2e/testkit/mocks/urlprovider.go
- test/e2e/tracing_test.go
- Push metrics and traces to telemetry-otlp-* and not mock backend
#85
> Fix OTLP push URL for E2E tests

- Dockerfile
- config/samples/http-mockserver.yaml
- main.go
- sec-scanners-config.yaml
- Downgrade Golang version to 1.20.4 for telemetry-manager
- Use fluent-bit image with Golang version 1.20.4
#220
> Downgrade Golang version to 1.20.4

- config/rbac/role.yaml
- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/tracepipeline/reconciler.go
- internal/resources/common/resources.go
- internal/resources/common/resources_test.go
- internal/resources/fluentbit/resources.go
- internal/resources/fluentbit/resources_test.go
- internal/resources/otelcollector/resources.go
- internal/resources/otelcollector/resources_test.go
- main.go
- metric gateway and trace collector are logging the following error recently: 
```
Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:kyma-system:telemetry-trace-collector" cannot list resource "replicasets" in API group "apps" at the cluster scope
```
- This reason is  https://github.com/open-telemetry/opentelemetry-helm-charts/issues/800
- This PR fixes the issue
Fixes https://github.com/kyma-project/telemetry-manager/issues/230
> update otel collector clusterrole

- .golangci.yaml
- internal/kubernetes/lock.go
- internal/kubernetes/lock_test.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/metricpipeline/reconciler_test.go
- internal/reconciler/tracepipeline/reconciler.go
- internal/reconciler/tracepipeline/reconciler_test.go
- test/e2e/metrics_test.go
- test/e2e/tracing_test.go
TracePipelines and MetricPipelines that stay in Pending state because of the limited allowed number of pipelines may still be applied to the Otel Collector configuration as the reconciliation logic lists all pipelines. This PR excludes above the limit from the configuration by utilizing the lock mechanism.
- Skip pending pipelines from collector config
https://github.com/kyma-project/telemetry-manager/issues/239
> Skip pending pipelines from collector config

- controllers/telemetry/logpipeline_controller_test.go
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/output.go
- internal/fluentbit/config/builder/output_test.go
- webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
In rare situation, Fluent Bit kept retrying malformed logs forever and thus block capacity of the file system buffer. To drop these records after a sufficient time, the retry count is limit to 300 by this PR.
- Limit Fluent Bit to 300 retries
https://github.com/kyma-project/kyma/issues/17662
> Limit Fluent Bit to 300 retries

- docs/contributor/installation.md
For the `Install Telemetry Manager in your cluster from latest release using the Lifecycle manager` section in the docs:
- Fix the typo of referencing the latest module template from the btp-manager repo
- Add the missing channel flag in the enable module command
- Reference the Kyma CLI installation link instead of using the kyma make target
> Fix installation guide typo

- Makefile
- config/manager/kustomization.yaml
- test/e2e/logging_test.go
- test/e2e/manager_test.go
- test/e2e/metrics_test.go
- test/e2e/telemetry_test.go
- test/e2e/testkit/matchers/log_matchers_test.go
- test/e2e/testkit/matchers/metric_matchers_test.go
- test/e2e/testkit/matchers/prometheus_matcher_test.go
- test/e2e/testkit/matchers/trace_matchers_test.go
- test/e2e/tracing_test.go
Adding more test-cases to the e2e-test suite make the test runs to take more time and also increased flakiness. This PR adds make targets to run the tests for a specific signal with the goal to improve the development workflow and have separate pipelines in future.
- Introduce make targets to run e2e tests per signal
> Introduce make targets to run e2e tests per signal

- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/tracepipeline/reconciler.go
- test/e2e/metrics_test.go
- test/e2e/tracing_test.go
The telemetry-operator created an OpenTelemetry Collector deployment if only one TracePipeline or MetricPipeline existed that had a missing secret reference. This caused to a crashing Collector since no exporter was configured. This PR changes the TracePipeline and MetricPipeline controller to reconcile the related Kubernetes objects online if at least one pipeline is ready for deployment.
- Reconcile Kubernetes objects only if at least one pipeline is ready for deployment
Closes: https://github.com/kyma-project/telemetry-manager/issues/272
> Fix otel-collector crash due to missing secret ref

- internal/otelcollector/config/builder/common/config_base_exporters.go
- internal/otelcollector/config/builder/common/otlpexporter/config_builder.go
- internal/otelcollector/config/builder/common/otlpexporter/config_builder_test.go
- internal/otelcollector/config/builder/common/otlpexporter/env_vars.go
- internal/otelcollector/config/builder/metric/gateway/config.go
- internal/otelcollector/config/builder/metric/gateway/config_builder.go
- internal/otelcollector/config/builder/metric/gateway/config_builder_test.go
- internal/otelcollector/config/builder/trace/gateway/config.go
- internal/otelcollector/config/builder/trace/gateway/config_builder.go
- internal/otelcollector/config/builder/trace/gateway/config_builder_test.go
The `otlpoutput` package was used to create configs for both `otlp` and `logging` exporters. This resulted in a strange API - it returned a map of exporters that had to be merged into the final map of exporters by the metric and trace gateway reconcilers. This PR splits it up so that the renamed `common/otlpexporter` package only takes care of creating the `otlp` exporter configuration. This has several advantages:
* Simplifies package API.
* The package adheres to the single responsibility principle - it only does what you expect it to do (`otlpexporter` build an `otlp` exporter config).
Not relevant since it's not a new feature. It's just an improvement of the existing code.
Tests conducted for …
> Refine otlpexporter package API

- config/manager/kustomization.yaml
- test/e2e/metrics_prometheus_test.go
- test/e2e/metrics_runtime_input_test.go
- test/e2e/metrics_workloads_input_test.go
- test/e2e/testkit/kyma/telemetry/metric/pipeline.go
- test/e2e/testkit/mocks/custom_metric_provider.go
- Add a simple e2e test that deploys a Pod that exposes some dummy metrics (taken from [this example](https://github.com/kyma-project/examples/tree/main/prometheus/monitoring-custom-metrics)). The Pod is annotated and is getting scraped by the metric agent. The test verifies that dummy metrics are present, but the kubelet metrics are not
- Simplify the kubelet metric test
https://github.com/kyma-project/kyma/issues/17828
It's an e2e test itself
> Add a simple Prometheus endpoint scraping e2e test scenario

- apis/operator/v1alpha1/telemetry_types.go
- config/busola/telemetry_busola_extension_cm.yaml
- config/crd/bases/operator.kyma-project.io_telemetries.yaml
- config/rbac/role.yaml
- controllers/operator/telemetry_controller.go
- controllers/operator/telemetry_controller_test.go
- docs/user/resources/01-telemetry.md
- internal/reconciler/telemetry/reconciler.go
- main.go
- test/e2e/manager_test.go
- test/e2e/suite_test.go
- test/e2e/telemetry_test.go
- test/e2e/testkit/k8s/telemetry.go
The Telemetry module CRD should be namespace scoped to be aligned with other Kyma modules. This PR updates the scope and related ClusterRole. Since a cluster scoped resource cannot be owned by a namespace scoped resource, the reconciliation of the ValidatingWebhookConfiguration had to be updated.
- Make Telemetry module CRD namespace scoped
- Update RBAC
- Change webhook reconciliation to not use owner references anymore
Closes: https://github.com/kyma-project/telemetry-manager/issues/286
Related issues: https://github.com/kyma-project/busola/issues/2512
> Make Telemetry CRD namspace scoped

- apis/telemetry/v1alpha1/shared_types.go
- config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- config/development/telemetry.kyma-project.io_metricpipelines.yaml
- docs/user/resources/04-tracepipeline.md
- docs/user/resources/05-metricpipeline.md
https://github.com/kyma-project/telemetry-manager/pull/347 added mTLS support for TracePipelines. The added TLS sub-resource of the CRD make the `insecure` flag mandatory. This PR makes the flag optional and defaults to `false`.
- Make insecure flag in OTLP TLS settings optional
Closes:
Related issues: https://github.com/kyma-project/kyma/issues/17995
> fix: Make insecure flag in tls config optional

- .commitlint.js
- .github/dependabot.yml
- .github/workflows/conventional-pr.yml
- .goreleaser.yaml
- docs/contributor/releasing.md
- Add a GitHub action to support PR title validation using the ConventionalCommits specification.
- Augment the goreleaser to adhere to the ConventionalCommits messages.
- Alter the Dependabot commit messages to fit into the ConventionalCommits expectations.
None
Irrelevant
Irrelevant 
Irrelevant
> chore: Integrate ConventionalCommits specification support to the SDLC

- main.go
- sec-scanners-config.yaml
- Bump directory-size-exporter to use Golang 1.21.0
Closes:
> chore: Bump directory-size-exporter to use Golang 1.21.0

- test/e2e/consts.go
- test/e2e/logging_annotation_test.go
- test/e2e/logging_exclude_container_test.go
- test/e2e/logging_label_test.go
- test/e2e/metrics_test.go
- test/e2e/tracing_test.go
Ginkgo's `Consistently` calls were used with different timeouts for similar purposes. This PR introduces two different timeouts, one for tests that wait for reconciliation, one for timeouts that wait for telemetry data delivery.
- Unify timeouts for Consistently usage
Closes:
> test: Unify timeouts for Consistently usage

- internal/reconciler/telemetry/reconciler.go
- test/e2e/telemetry_test.go
The Telemetry CRD controller reconciles the ValidatingWebhookConfiguration for the LogPipeline and LogParser CRDs. The reconciliation of the webhook was stopped after the Telemetry CR had a deletion timestamp. This could lead an expiring certificate while waiting for remaining pipelines. The PR changes the behaviour to reconcile the webhook until all pipelines are deleted.
- Reconcile webhook while waiting for module deletion
Closes:
> fix: Reconcile webhook while waiting for module deletion

- config/busola/telemetry_busola_extension_cm.yaml
- added detail view for telemetry resource to indicate the status
Closes:
> feat: Show module status in busola view

- Dockerfile
- config/samples/http-mockserver.yaml
- internal/otelcollector/config/metric/agent/receivers.go
- internal/otelcollector/config/metric/agent/receivers_test.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
- main.go
- sec-scanners-config.yaml
- test/e2e/metrics_runtime_input_test.go
- test/testkit/mocks/backend/deployment.go
- update to otel-collector 0.87.0
- update to fluentbit 2.1.10
- update to latest directory-size-exporter
- The otel-collector update introduced a breaking change to the kubeletstatsreceiver, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.87.0). The insecure_skip_verify flag was ignored. Not it gets honored and as the default value is false, it broke the setup. I switched it to true for now as on Gardener it seems to be not able to verify the used certificate. A follow-up needs to be done on how we could disable it.
- The new metrics exported by the kubeletstatsreceiver are all optional and need to get enabled explicitly
Closes:
https://github.com/kyma-project/third-party-images/pull/388 …
> feat: Update to otel-collector 0.87.0 and fluentbit 2.1.10

- internal/otelcollector/config/trace/gateway/processors.go
- internal/otelcollector/config/trace/gateway/processors_test.go
- test/testkit/otlp/traces/helpers.go
The trace filter rule changed in https://github.com/kyma-project/telemetry-manager/pull/468 about the /healthz endpoint was wrong. The test was adjusted right to use the "Egress" operation but the filter rule was still filtering for "Ingress"
All spans created by the istio-ingressgateway are of type "egress", there is no point in filtering for "ingress"
I adjusted the rule.
Still not clear how the change could have been merged in first place. Most probably there is a flakyness on receiving spans which at the merge was kicking-in so that the span was wrongly assumed to be filtered out. Currently the tests on main are failing.
- Adjusted the rule to be correct as demanded by the test
Closes:
The feature is …
> fix: Fix noisy span filter rule for healthz endpoint

- .github/workflows/pull-governance.yml
- Makefile
There is no make target available to run e2e tests local on an existing cluster. This is very inconvenient when running tests against an existing installation. This PR splits up the existing targets to be independent on the cluster and manager installation while keeping the k3d based targets. 
- split up the test targets to have a version based on k3d and a version not based on any cluster
- Adjust gardener integration test to use the cluster-less targets
- Adjusted governance github action to not get triggered twice
Closes:
> chore: Introduce test targets not requiring k3d

- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/logpipeline/status.go
- If LogPipeline is defined with `grafana-loki` output, it should stay in `Pending` State and considered undeployable only if it has a non-empty url.
Closes:
#461
> fix: Consider LogPipeline undeployable only if grafana-loki output is defined with non-empty url

- test/e2e/metrics_service_name_test.go
- test/e2e/traces_service_name_test.go
- On a Gardener cluster, API server proxy traffic is routed through vpn-shoot, so service.name is set respectively
> test: Fix E2E tests on Gardener

- test/integration/istio/metrics_otlp_input_test.go
- test/testkit/periodic/periodic.go
- test/testkit/verifiers/objects.go
We recently changed the operator do to not watch Secrets outside the system namespace and lowered the periodic reconciliation frequency to 60s to compensate this. This change might have caused some test flakyness since gomega's Eventually blocks retried only for 60 seconds. This PR increases the timeout to ensure a reconciliation in rare cases.
- Increase timeout for gomega.Eventually blocks to 120s
Closes:
Related issues: https://github.com/kyma-project/telemetry-manager/issues/464, https://github.com/kyma-project/telemetry-manager/pull/489
> test: Increase timeout for gomega.Eventually blocks

- Makefile
- config/manager/kustomization.yaml
- main.go
- module-config-dev.yaml
- module-config.yaml
- sec-scanners-config.yaml
- bumped the operator image and module version in preparation of releasing version 1.5.0
- bumped image for directory-size-exporter
> chore: Bump images and module version for releasing 1.5.0

- main.go
- sec-scanners-config.yaml
- Update directory-size-exporter to use Go 1.21.5
- https://github.com/kyma-project/directory-size-exporter/pull/37
> chore: Update directory-size-exporter to use Go 1.21.5

- test/testkit/verifiers/daemonset.go
- test/testkit/verifiers/deployment.go
- test/testkit/verifiers/logs.go
- test/testkit/verifiers/metrics.go
- test/testkit/verifiers/monitoring.go
- test/testkit/verifiers/objects.go
- test/testkit/verifiers/telemetry.go
- test/testkit/verifiers/traces.go
- Since Gomega matcher imports were whitelisted in https://github.com/kyma-project/telemetry-manager/pull/612, we can now use dot imports also in the `testkit`, which makes the code much more readable and easier to write
- https://github.com/kyma-project/telemetry-manager/pull/612
> chore: Use dot import for gomega matchers in testkit

- Makefile
- hack/release.sh
- Avoid adding remote origin in the release script. This is not needed anymore since the release target is now being executed in a GitHub action and the remote origin is already added in the [Checkout repo](https://github.com/kyma-project/telemetry-manager/blob/main/.github/workflows/push-release.yml#L11) step. Attempting to add the remote origin after it has already been added causes an error.
- Kyma cli is not a dependency anymore for the release make target, since we are not creating the ModuleTemplate in the release script anymore.
- #566
> chore: Avoid adding remote origin in release script

- .github/workflows/push-release.yml
- For the `GitHub Release` workflow, add the `GITHUB_TOKEN` environment variable in the step in which we run the release make target. This is needed so that `goreleaser` can publish a GitHub release
- #566
> chore: Add GITHUB_TOKEN env when running release make target

- .github/workflows/push-release.yml
- By default, the [Checkout](https://github.com/actions/checkout) GitHub action only fetches a single commit. As a result, goreleaser will not be able to create the changelogs since the previous tags are not fetched. We need to set `fetch-depth: 0` to fetch all tags as documented [here](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches).
- #566
> chore: Fetch all history in Github Release workflow

- docs/user/02-logs.md
PR #590 changed the Fluent Bit configuration to use one Kubernetes filter per LogPipeline. This also avoids filters for JSON manipulation that used the `__kyma__` attribute prefix.
- Remove obsolete log attribute prefix limitations
- https://github.com/kyma-project/telemetry-manager/issues/479
- https://github.com/kyma-project/telemetry-manager/pull/590
> docs: Remove obsolete log attribute prefix limitations

- docs/contributor/arch/002-fluent-bit-without-file-system-buffer.md
- Update Fluent Bit config ADR to document reasons to keep the filesystem buffer
- https://github.com/kyma-project/telemetry-manager/issues/479
> docs: Update Fluent Bit Config ADR

- Makefile
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Create 1.5.1 release to fix: https://github.com/kyma-project/telemetry-manager/issues/614
- Picked image from: https://storage.googleapis.com/kyma-prow-logs/logs/post-telemetry-manager-build/1735212402510663680/build-log.txt
-
> chore: Create release 1.5.1

- .github/template/setup-golang/action.yaml
- .github/workflows/pull-code-checks.yml
- .github/workflows/pull-docu-checks.yml
- .github/workflows/pull-github-checks.yml
- docs/user/README.md
- Fixed broken link in docu
- Refactored github actions so that markdown checker is running on all commits, even if only docu changes are done
- https://github.com/kyma-project/directory-size-exporter/pull/39
> fix: Fixed link in docu and adjusted code checks to run also on docu changes only

- internal/resources/otelcollector/agent.go
- internal/resources/otelcollector/agent_test.go
- internal/resources/otelcollector/core.go
- internal/resources/otelcollector/gateway_test.go
- test/integration/istio/metrics_istio_input_test.go
- Do not intercept outgoing connections from metric agent by Istio
- https://github.com/kyma-project/telemetry-manager/issues/606
> fix: Do not intercept outgoing connections from metric agent by Istio

- docs/user/README.md
- docs/user/resources/05-metricpipeline.md
- Remove leftover notes about metrics feature unavailability, since the feature will become available in the next release in fast channel
- #623
> docs: Remove leftover notes about metrics feature unavailability

- docs/user/resources/01-telemetry.md
- docs/user/resources/05-metricpipeline.md
- internal/conditions/conditions.go
- internal/reconciler/metricpipeline/status.go
- internal/reconciler/metricpipeline/status_test.go
- internal/reconciler/telemetry/log_components_checker_test.go
- internal/reconciler/telemetry/metric_components_checker.go
- internal/reconciler/telemetry/metric_components_checker_test.go
- internal/reconciler/telemetry/trace_components_checker_test.go
- internal/reconciler/tracepipeline/status.go
- internal/reconciler/tracepipeline/status_test.go
- test/e2e/metrics_multi_pipeline_test.go
- The old reason/message was `WaitingForLock`, which is too technical from an end-user perspective. This PR renames it to `MaxPipelinesExceeded`, which is much more intuitive. The change affects both Metric and Trace Pipeline
- https://github.com/kyma-project/telemetry-manager/issues/563
> feat: Enhance Status Message for Max Pipeline Count Exceeded

- docs/user/integration/dynatrace/README.md
- docs/user/integration/jaeger/README.md
- docs/user/integration/loki/README.md
- docs/user/integration/opentelemetry-demo/README.md
- docs/user/integration/sap-cloud-logging/README.md
- Fix link to documentation for enabling module
-
> docs: Fix link to documentation for enabling module

- config/manager/manager.yaml
- Add the missing `metric-gateway-priority-class` argument when running the `manager` container. In the [PR](https://github.com/kyma-project/telemetry-manager/pull/629) for including the metrics feature in releases, we removed the Kustomize [patch](https://github.com/kyma-project/telemetry-manager/pull/629/files#diff-d509a51c050a776d450eb1d1da96db70a31e7f1a0dc0fbe5a2d081bd30b72a53) for the manager deployment, as it was not needed anymore, since the metrics feature will be enabled by default. However, it was forgotten to copy over the argument for the `metric-gateway-priority-class` to the manager deployment.
- #623
> fix: Add missing metric-gateway-priority-class argument

- test/integration/istio/metrics_istio_input_test.go
- PR #609 fixed a but to not intercept the metric scraping of Istio proxies, which was indicated by wrong metric attributes. This PR enhances the corresponding integration test to validate that Istio metrics have the right attribute values.
- https://github.com/kyma-project/telemetry-manager/issues/606
> test: Validate Istio metric attributes

- apis/telemetry/v1alpha1/shared_types.go
- config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
- config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- config/samples/telemetry_v1alpha1_metricpipeline.yaml
- docs/user/resources/04-tracepipeline.md
- docs/user/resources/05-metricpipeline.md
- internal/otelcollector/config/exporters.go
- internal/otelcollector/config/metric/gateway/config_builder.go
- internal/otelcollector/config/otlpexporter/config_builder.go
- internal/otelcollector/config/otlpexporter/config_builder_test.go
- internal/otelcollector/config/otlpexporter/env_vars.go
- internal/otelcollector/config/trace/gateway/config_builder.go
- test/e2e/metrics_endpoint_path_validation_test.go
- test/e2e/metrics_endpoint_with_path_test.go
- test/e2e/traces_endpoint_path_validation_test.go
- test/e2e/traces_endpoint_with_path_test.go
- test/testkit/kyma/common_names.go
- test/testkit/kyma/env.go
- test/testkit/kyma/telemetry/metric/pipeline.go
- test/testkit/kyma/telemetry/trace/pipeline.go
- test/testkit/verifiers/secret.go
- Add new field `path` to the OTLPEndpoint
- Add validation rule check field `path` only valid with `protocol` HTTP
- When additional path configured with HTTP protocol, end URL should be used as is by the OTEL Collector (no auto append path `/v1/metrics | traces`)
- https://github.com/kyma-project/telemetry-manager/issues/594
> feat: Add support additional endpoint path

- internal/reconciler/telemetry/status.go
- internal/reconciler/telemetry/status_test.go
- Fix wrong metric pipeline status check in module status endpoint
-
> fix: Metric gateway endpoint not set in module status

- Makefile
- test/integration/istio/traces_test.go
- Reduce the number of tests that are being executed on the gardener cluster.
- Execute istio integration tests as of now.
- Reduce the size of the VM
- Remove k8s attribute node check to be able to execute the test on k3d and gardener as well
- Tested on n1-standard-4
-
> fix: Improve stability of post-submit job

- internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
- internal/otelcollector/config/trace/gateway/processors_test.go
- internal/otelcollector/config/trace/gateway/testdata/config.yaml
-  Remove unused internal kyma prometheus rule as we dont have prometheus anymore.
- https://github.com/kyma-project/telemetry-manager/issues/621
> feat: Remove unused kyma prometheus filter rule

- .github/workflows/pull-code-checks.yml
- .testcoverage.yml
- Makefile
- controllers/operator/suite_test.go
- controllers/telemetry/suite_test.go
- webhook/logpipeline/webhook_suite_test.go
- Add a new make target to check unit test coverage using `go-test-coverage`
- Add a GitHub action
- Add an option to skip envtests, since they are not needed for the coverage
- Rename `linting` to `lint`
-
> chore: Set up unit test coverage check

- docs/user/gateways.md
- internal/otelcollector/config/gatewayprocs/resolve_service_name_proc.go
- internal/otelcollector/config/gatewayprocs/resolve_service_name_proc_test.go
- internal/otelcollector/config/metric/gateway/testdata/config.yaml
- internal/otelcollector/config/trace/gateway/testdata/config.yaml
- test/e2e/metrics_service_name_test.go
- test/e2e/traces_service_name_test.go
- test/integration/istio/metrics_otlp_input_test.go
- test/testkit/mocks/servicenamebundle/service_name_bundle.go
- test/testkit/mocks/telemetrygen/telemetrygen.go
- Enrich the service.name attribute if its value follows the "unknown_service:<process.executable.name>" pattern
- Adjust unit tests
- Add e2e tests
- #565
> feat: Enrich the service.name attribute if its value follows the "unknown_service:<process.executable.name>" pattern

- .github/workflows/post-release.yml
- Makefile
- config/manager/kustomization.yaml
- docs/contributor/releasing.md
- sec-scanners-config.yaml
- Use `main` tag for telemetry-manager image
- Bump goreleaser to 1.23.0
- Update release docs
- https://github.com/kyma-project/telemetry-manager/issues/656
> chore: Improve release workflow

- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/logpipeline/reconciler_test.go
- The checksum generation missed including the tls secret. So changing tls secret would not restart the fluent-bit daemonset.
- https://github.com/kyma-project/telemetry-manager/issues/670
> fix: Restart Fluent Bit after mTLS certificate changed

- test/e2e/traces_noisy_span_filter_test.go
- test/testkit/otlp/traces/helpers.go
- We have recently removed the filter rule,  but forgot to adjust the E2E tests
- https://github.com/kyma-project/telemetry-manager/pull/667
> test: Fix noisy span filter E2E test

- Makefile
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Bump telemetry-manager image for releasing version 1.6.1
-
> chore: Bump telemetry-manager image for releasing version 1.6.1

- .github/dependabot.yml
- fixed the label used by dependabot to be in sync with the actual repo labels
-
> chore: Fix dependabot labelling

- docs/user/gateways.md
- internal/otelcollector/config/gatewayprocs/resolve_service_name_proc.go
- internal/otelcollector/config/gatewayprocs/resolve_service_name_proc_test.go
- internal/otelcollector/config/metric/gateway/testdata/config.yaml
- internal/otelcollector/config/trace/gateway/testdata/config.yaml
- test/e2e/metrics_service_name_test.go
- test/e2e/traces_service_name_test.go
- test/testkit/mocks/servicenamebundle/service_name_bundle.go
- Improve regexp for detecting the `unknown_service pattern:<process.executable.name>` in the service.name attribute
- Adjust the documentation
- Adjust unit tests
- Add e2e tests to ensure that `service.name` attribute is NOT enriched when its value is not following the `unknown_service:<process.executable.name>` pattern
- #565
> feat: Improve regexp for detecting the unknown_service pattern in the service.name attribute

- test/e2e/metrics_secret_rotation_test.go
- test/e2e/traces_secret_rotation_test.go
- Modify the assertion logic to verify the absence of the Gateway until it is Eventually not found, as opposed to using Consistently. We have noticed occasional test failures, which may be linked to leftover Gateway deployments from prior test executions that were not successfully deleted
-
> test: Fix flaky E2E metrics tests (missing Secret)

- Makefile
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Bump telemetry-manager image for releasing version 1.7.0
-
> chore: Bump telemetry-manage image for releasing 1.7.0

- docs/user/integration/loki/README.md
- Use non headless-service for loki in the loki pipeline. 
- As with headless service the loki headless service uses the ip address from the loki pod. If for any reason the loki pod is restarted then the cached ip address of loki in fluent-bit pod is not updated and can cause log loss.
-
> docs: Use non headless service for loki example

- docs/user/README.md
- docs/user/integration/README.md
- docs/user/integration/opentelemetry-demo/README.md
- Add missing space
- separate links to integration guides to have them more obvious separated by category
-
> docs: Add missing space and separate links to integration guides

- main.go
- sec-scanners-config.yaml
- Bump image of directory-size-exporter
-
> chore: Bump directory-size-exporter

- .github/workflows/pr-lifecycle.yml
- Makefile
- Fixed a problem introduced in https://github.com/kyma-project/telemetry-manager/pull/742 (wrong step order)
- Enable metrics suite in upgrade tests
-
> test: Fix upgrade test

- Makefile
Please enter the commit message for your changes. Lines starting
- Flake attempt can mask the actual error, so remove it.
-
> test: Remove Flake attempts

- docs/contributor/governance.md
- docs/user/integration/dynatrace/README.md
- Updated a broken link
- Removed a link to a non-existing section from the ToC
- Testing the new custom link checker
> docs: Fix links

- docs/contributor/arch/004-consolidate-pipeline-statuses.md
- Add an ADR, describing steps to unify LogPipeline, TracePipeline, and MetricPipeline statuses
https://github.com/kyma-project/telemetry-manager/issues/712
> docs: ADR: Consolidate Telemetry Pipeline Statuses

- docs/contributor/assets/otel-logs-values.yaml
- docs/contributor/pocs/otlp-logs.md
- Add documentation about OpenTelemetry logging PoC
- https://github.com/kyma-project/telemetry-manager/issues/720
> docs: Add OTLP Logs PoC documentation

- docs/contributor/arch/007-log-pipeline-otlp-output.md
- Add an ADR describing a new OTel Collector-based LogPipeline OTLP Output 
- https://github.com/kyma-project/telemetry-manager/issues/712
> docs: ADR LogPipeline OTLP Output

- main.go
- Some time ago a `PprofBindAddress` was introduced in `controller-runtime`, which allows us to spare some code. This PR makes use of this hand instead of setting up pprof manually
-
> chore: Simplify pprof server set up

- .github/workflows/branch-integration.yml
- Makefile
- Adjusted the gardener integration job to test on current and next k8s version
-
> chore: Test compatibility with next k8s version 1.28

- Makefile
- Length of cluster in gardener integration test exceeds 15 characters and is not valid, fixed that by shortening it
- https://github.com/kyma-project/telemetry-manager/pull/754
> chore: Fix length of cluster for gardener integration test

- .github/workflows/branch-integration.yml
- Makefile
- The env variable for determining the k8s version was applied to the wrong github action step, this PR fixes it
- https://github.com/kyma-project/telemetry-manager/pull/774
> chore: Fix env variable injection for gardener integration test

- internal/fluentbit/config/builder/input.go
- internal/fluentbit/config/builder/input_test.go
- test/e2e/logs_exclude_namespaces_test.go
- test/e2e/logs_include_namespaces_test.go
- test/testkit/k8s/log_pipeline.go
- test/testkit/kyma/common_names.go
- test/testkit/matchers/log/log_matchers.go
- Exclude system namespaces in LogPipelines only if no other includes or excludes set
- https://github.com/kyma-project/telemetry-manager/issues/778
> fix: Exclude system namespaces correctly

- docs/user/integration/dynatrace/README.md
- Link to Dynatrace docs was broken
-
> docs: Fix link to Dynatrace docs about aggregation temporality

- .github/workflows/pr-lifecycle.yml
- Wait for telemetry-manager instead of telemetry-operator in upgrade test
- #813
> fix: Change manager deployment name in upgrade test

- controllers/telemetry/logpipeline_controller_test.go
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/kubernetes_filter.go
- internal/fluentbit/config/builder/kubernetes_filter_test.go
- webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
- Increase buffer size of Fluent Bit's Kubernetes filter. The previous buffer size caused missing Kubernetes metadata in situations where the buffer size was not sufficient.
- https://github.com/kyma-project/telemetry-manager/issues/834
> fix: Increase Fluent Bit Kubernetes filter buffer

- Makefile
- Determine supported gardenlinux version automated
- Configure the version in the CLI command
-
> chore: Determine supported gardenlinux version automated for gardener integration test

- internal/resources/otelcollector/agent.go
- internal/resources/otelcollector/agent_test.go
- Disabling the traffic interception for the telemetry-metric-gateway did not work properly and caused errors while scraping some workloads like Fluent Bit. This changes the Istio annotations for the telemetry-trace-gateway to exclude all outgoing connections except pushing metrics to the gateway.
- #824
> fix: Exclude metric scraping from Istio interception

- config/manager/kustomization.yaml
- internal/conditions/conditions.go
- internal/conditions/conditions_test.go
- internal/reconciler/logparser/status_test.go
- internal/reconciler/logpipeline/status_test.go
- internal/reconciler/telemetry/log_components_checker.go
- internal/reconciler/telemetry/metric_components_checker.go
- internal/reconciler/telemetry/trace_components_checker.go
- internal/reconciler/tracepipeline/status_test.go
Tackling the suggestions from the comments in #833
- Rename `CommonMessageFor` function to `MessageFor` in order to have a better reflection of its new logic
- Remove `removePendingAndRunningConditions` function from both `traceComponentsChecker` and `logComponentsChecker`. The deprecated conditions (`Running` and `Pending`) are already ignored in the `firstUnhealthyPipelineReason` function
- Remove extra `newTag` field in manager kustomization
- #805
> chore: Refactor status handling

- config/manager/manager.yaml
- internal/reconciler/telemetry/reconciler.go
- internal/resources/selfmonitor/resources.go
- internal/resources/selfmonitor/resources_test.go
- internal/selfmonitor/config/config.go
- internal/selfmonitor/config/config_builder.go
- internal/selfmonitor/config/config_builder_test.go
- internal/selfmonitor/config/testdata/config.yaml
- main.go
- Relax the network policy as self monitor is not able to fetch services from api server
- Add priority class
- Restrict config to namespace
- https://github.com/kyma-project/telemetry-manager/issues/822
> fix: Add priority class and fix network policy

- hack/gardener-integration-test.sh
- The ginkgo path is not set so branch integration job fails
```
hack/gardener-integration-test.sh: line 19: /ginkgo: No such file or directory
```
- Also fix the image name
-
> fix: Get the Ginkgo path properly

- internal/otelcollector/config/metric/agent/config.go
- internal/otelcollector/config/metric/agent/receivers.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
- test/testkit/otel/kubeletstats/metrics.go
- Add configuration capabilities for kubeletstatreceiver to enable or disable metrics
- Disable deprecated *.cpu.utilization metrics
- Enable *.cpu.usage metrics
- Update unit and e2e test accordingly new configuration changes  
- https://github.com/kyma-project/telemetry-manager/issues/838
> feat: Add cpu.usage metrics and disable cpu.utilization metrics

- main.go
- Manager initialization error handling happened after accessing the manager instance, in case of any initialization error the manger instance will be nil
-
> fix: Bug fix manager initialization error handling

- Dockerfile
- The `/workspace` directory is used by kaniko executor as well and it overlaps during build
-
> chore: Change the name of the WORKDIR in Dockerfile

- internal/reconciler/telemetry/reconciler.go
- internal/resources/otelcollector/agent.go
- internal/resources/otelcollector/agent_test.go
- internal/resources/otelcollector/config.go
- internal/resources/otelcollector/core.go
- internal/resources/otelcollector/gateway.go
- internal/resources/otelcollector/gateway_test.go
- internal/resources/selfmonitor/config.go
- internal/resources/selfmonitor/resources.go
- internal/resources/selfmonitor/resources_test.go
- internal/selfmonitor/config/config.go
- internal/selfmonitor/config/config_builder.go
- internal/selfmonitor/config/testdata/config.yaml
- main.go
- Add scrape-config for self-monitor
- Add the missing servicer for self-monitor
- https://github.com/kyma-project/telemetry-manager/issues/822
> feat: Add scrape config for self-monitor

- internal/conditions/conditions.go
- internal/conditions/conditions_test.go
- internal/reconciler/logparser/status.go
- internal/reconciler/logparser/status_test.go
- internal/reconciler/logpipeline/status.go
- internal/reconciler/logpipeline/status_test.go
- internal/reconciler/tracepipeline/status.go
- internal/reconciler/tracepipeline/status_test.go
- test/testkit/verifiers/logs.go
- test/testkit/verifiers/traces.go
- Ensure that the `Pending` condition always exists in the conditions list for `TracePipeline`, `LogPipeline` and `TracePipeline`
- If a pipeline was in a pending condition and then it becomes deployable, this will result in the `Trace Gateway` / `Fluent Bit` to restart. Therefore, when handling the running condition, we can always set the reason for the false pending condition to be `FluentBitDaemonSetNotReady` for `LogPipeline` and `TraceGatewayDeploymentNotReady` for `TracePipeline`
- Rename `SetRunningCondition` func to `HandleRunningCondition` to avoid giving the false impression that it only sets the `Running` condition to True
- Rename `SetPendingCondition` func to `HandlePendingCondition` to avoid giving the false …
> fix: Ensure pending condition is always preserved

- docs/contributor/governance.md
- The existing link https://golangci-lint.run/usage/integrations/ is now changed to https://golangci-lint.run/welcome/integrations/
-
> chore: Update link for golangci-lint integration

- hack/lint-manifests.sh
- Update the lint-manifests script to ensure that the auto-generated CRDs for development variant are always up-to-date
- #848
> feat: Ensure that auto-generated CRDs for development variant are always up-to-date

- hack/release.sh
- Detect the previous release tag and set the environment variable GORELEASER_PREVIOUS_TAG
- https://github.com/kyma-project/telemetry-manager/issues/808
> fix: Explicitly set previous release tag to fix the auto-generated changelogs

- apis/telemetry/v1alpha1/shared_types.go
- apis/telemetry/v1beta1/shared_types.go
- config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
- config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- internal/otelcollector/config/metric/gateway/config_builder.go
- internal/otelcollector/config/otlpexporter/config_builder.go
- internal/otelcollector/config/otlpexporter/config_builder_test.go
- internal/otelcollector/config/trace/gateway/config_builder.go
- internal/selfmonitor/flowhealth/prober.go
- internal/selfmonitor/flowhealth/prober_test.go
- test/testkit/k8s/metric_pipeline_v1beta1.go
- test/testkit/k8s/trace_pipeline_v1beta1.go
- Refactor the otlpexporter.ExporterID helper method
- Fix a bug resulting in reflecting a problem for one pipeline in the status of another pipeline, if their names overlap
- Match otlp/ and otlphttp/ prefixes
- https://github.com/kyma-project/telemetry-manager/issues/822
> fix: Self-monitor alert matching

- controllers/operator/suite_test.go
- controllers/operator/telemetry_controller.go
- controllers/telemetry/logparser_controller.go
- controllers/telemetry/logpipeline_controller.go
- controllers/telemetry/metricpipeline_controller.go
- controllers/telemetry/suite_test.go
- controllers/telemetry/tracepipeline_controller.go
- main.go
In the early stage of the project, we made a clear distinction between Controllers and Reconcilers. The Controllers were designed to establish reconciliation triggers (SetupWithManager) and to call upon Reconcilers to perform the actual reconciliation of a custom resource. Importantly, the Controllers and Reconcilers are located in separate packages.
However, a slight inconsistency arose with the use of terminology. While we applied the term 'Controller' in the context of package names, variables, and file names, the actual types were termed 'Reconcilers'. This understandably led to some confusion. To solve this issue and improve clarity, this PR is aimed at unifying the terminology.
Changes refer to particular issues, PRs or …
> chore: Unify Controller/Reconciler type names

- hack/load-tests/log-fluentbit-test-setup.yaml
- hack/load-tests/metric-agent-test-setup.yaml
- hack/load-tests/metric-load-test-setup.yaml
- hack/load-tests/run-load-test.sh
- hack/load-tests/trace-load-test-setup.yaml
- main.go
- sec-scanners-config.yaml
- test/testkit/mocks/backend/config_map.go
- test/testkit/mocks/backend/deployment.go
Currently a warning pops up in the startup phase of each otel-collector instance:
```json
{"level":"warn","ts":1710287522.1744921,"caller":"localhostgate/featuregate.go:63","msg":"The default endpoints for all servers in components will change to use localhost instead of 0.0.0.0 in a future version. Use the feature gate to preview the new default.","feature gate ID":"component.UseLocalHostAsDefaultHost"}
```
- Add feature gate to the otel-collector command to switch already to the new default in order to suppress the warning
- ...
- ...
- https://github.com/kyma-project/third-party-images/pull/422
> fix: Suppress otel-collector warning at startup by using localhost as default

- main.go
- sec-scanners-config.yaml
- Update directory-size-exporter to use Golang 1.22.2
- https://github.com/kyma-project/directory-size-exporter/pull/51
> chore: Update directory-size-exporter to use Golang 1.22.2

- internal/selfmonitor/webhook/handler.go
- internal/selfmonitor/webhook/handler_test.go
- Set content-security-policy header in webhook handler
-
> fix: Set content-security-policy header in webhook handler

- test/e2e/logs_basic_v1alpha1_test.go
- test/e2e/logs_basic_v1beta1_test.go
- Sometimes the logpipeline test fails with error that "object is being deleted: logpipelines.telemetry.kyma-project.io "http-output-pipeline" already exists". The pipeline name is same for alpha1 and beta1 tests so use different pipeline names.
-
> fix: Flakiness in the logppipeline tests

- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/logpipeline/status.go
- internal/tls/cert/tls_cert_validator.go
- Currently if the secret is missing for TLS Cert, we still check if cert is valid or not. Thus overriding the status `ReferenceSecretMissing`. 
-
> fix: Invocation order for setting the status

- .env
- .github/workflows/branch-integration.yml
- Update kubernetes version for integration tests to 1.28
-
> chore: Update kubernetes version for integration tests

- .github/workflows/pr-integration.yml
- test/e2e/logs_self_monitor_basic_test.go
- Add e2e test for LogPipeline health condition
- #917
> test: Add e2e test for LogPipeline health condition

- internal/reconciler/telemetry/reconciler.go
- internal/selfmonitor/config/config_builder.go
- internal/selfmonitor/config/expr_builder.go
- internal/selfmonitor/config/fluent_bit_rule_builder.go
- internal/selfmonitor/config/otelcol_rule_builder.go
- internal/selfmonitor/config/rules.go
- internal/selfmonitor/config/rules_test.go
- internal/selfmonitor/config/testdata/config.yaml
- internal/selfmonitor/prober/log_pipeline_prober.go
- internal/selfmonitor/prober/otel_pipeline_prober.go
- internal/selfmonitor/webhook/handler.go
- Optimize self-monitor memory consumption by whitelisting the exact metrics we are scraping there
- This change tightly couples the alertrules and config pkgs, so they were merged into one
-
> feat: Whitelist metrics scraped by self-monitor

- .env
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Bump the manager image according to https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/releasing.md
-
> chore: Bump images for 1.13.1 release

- .golangci.yaml
- apis/telemetry/v1alpha1/secret_refs_test.go
- apis/telemetry/v1beta1/secret_refs_test.go
- controllers/telemetry/logpipeline_controller_test.go
- internal/k8sutils/daemonset.go
- internal/k8sutils/daemonset_test.go
- internal/k8sutils/deployment.go
- internal/k8sutils/deployment_test.go
- internal/k8sutils/utils.go
- internal/logger/logger.go
- internal/otelcollector/config/otlpexporter/config_builder.go
- internal/reconciler/logparser/reconciler.go
- internal/reconciler/logparser/status.go
- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/logpipeline/status.go
- internal/reconciler/logpipeline/sync.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/telemetry/status.go
- internal/reconciler/tracepipeline/reconciler.go
- internal/reconciler/tracepipeline/status.go
- internal/resources/otelcollector/config.go
- internal/selfmonitor/config/config_builder.go
- internal/webhookcert/ca_cert_provider.go
- internal/webhookcert/server_cert_provider.go
- test/testkit/k8s/objects.go
- test/testkit/matchers/log/log_matchers.go
- test/testkit/matchers/metric/metric_matchers.go
- test/testkit/matchers/trace/trace_matchers.go
- test/testkit/matchers/unmarshal.go
- test/testkit/mocks/backend/backend.go
- enable predeclared linter
- enable copyloopvar linter
- enable wastedassign linter
- enable errname linter
- enable errorlint linter
- https://github.com/kyma-project/telemetry-manager/issues/114
> chore: Enable more linters

- internal/reconciler/telemetry/log_components_checker.go
- internal/reconciler/telemetry/log_components_checker_test.go
- internal/reconciler/telemetry/reconciler.go
- internal/selfmonitor/config/expr_builder.go
- internal/selfmonitor/config/fluent_bit_rule_builder.go
- internal/selfmonitor/config/rules_test.go
- internal/selfmonitor/prober/common.go
- internal/selfmonitor/prober/log_pipeline_prober.go
- internal/selfmonitor/prober/otel_pipeline_prober.go
- internal/selfmonitor/webhook/handler.go
- Reflect LogPipeline flow health status in the Telemetry status
Also, the following improvement after a discussion with @k15r 
- Fix a potentially leaky connection in the self-monitor webhook handler
- Extend expression builder to improve FB buffer usage rules readability
- Improve variable and func names
- https://github.com/kyma-project/telemetry-manager/issues/917
> feat: Reflect LogPipeline flow health status in the Telemetry status

- .env
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Bump telemetry-manager image for 1.14.0 release
-
> chore: Bump telemetry-manager image for 1.14.0 release

- docs/user/resources/01-telemetry.md
- docs/user/resources/02-logpipeline.md
- docs/user/resources/04-tracepipeline.md
- docs/user/resources/05-metricpipeline.md
- internal/conditions/conditions.go
- internal/reconciler/telemetry/metric_components_checker_test.go
- internal/reconciler/telemetry/trace_components_checker_test.go
- The idea of linking TelemetryFlowHealth to other conditions didn't work well and caused more problems than it solved. So, this PR now adjusts the status messages to better match the telemetry flow, even when there's no flow but no issues exist either.
- Unify existing messages (gateway vs controller, unable vs Unable, etc.)
- https://github.com/kyma-project/telemetry-manager/issues/917
> feat: Adjusted the FlowHealthy status condition messages

- docs/contributor/arch/011-kymastatsmetrics.md
- Add ADR for module status metrics
- #921
> docs: Add ADR for module status metrics

- main.go
- sec-scanners-config.yaml
- Updated prometheus to latest patch version. Patch does not contain relevant fixes, however uses a newer golang version
- https://github.com/kyma-project/third-party-images/pull/431
> feat: Update to prometheus 2.45.5 in self-monitor

- .env
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Bump telemetry-manager image for 1.15.0 release
-
> chore: Bump telemetry-manager image for 1.15.0 release

- internal/resources/fluentbit/resources.go
- internal/resources/fluentbit/resources_test.go
- We already added sidecar injection labels to OTel Collector pods, but not for Fluent Bit. This PR aligns Fluent Bit with OTel Collector with regard to labeling. It's important to note that there aren't any Istio-specific features for LogPipelines yet, so it doesn't change existing functionality.
-
> feat: Enable sidecar injection for Fluent Bit by default

- hack/gardener-integration-test.sh
- Do not execute self-monitor istio tests in Gardener suite
-
> test: Do not execute self-monitor istio tests in Gardener suite

- internal/reconciler/logpipeline/sync.go
- In case of a non-deployable LogPipeline, the `OwnerReference` was not set in the `telemetry-fluent-bit-sections` ConfigMap. Therefore, if this non-deployable LogPipeline is deleted, the `telemetry-fluent-bit-sections` ConfigMap will not be cleaned up and it will remain orphaned in the cluster. This is fixed in this PR by setting the `OwnerReference` in the `telemetry-fluent-bit-sections` ConfigMap regardless of whether the LogPipeline is deployable or not.
> fix: Always set OwnerReference for telemetry-fluent-bit-sections ConfigMap

- .github/dependabot.yml
- ignore fluent-bit docker file versions
-
> chore: Ignore dependabot updates for fluent-bit

- config/busola/telemetry_busola_extension_cm.yaml
- The telemetry module view in the Kyma dashboard is not getting displayed at the moment as it get overruled by the new Istio telemetry view. Fixed it by using a custom UI path for the telemetry view
- https://github.com/kyma-project/istio/issues/579
> fix: Use different UI path for telemetry module view to not clash with Istio resources

- internal/k8sutils/owner_reference_setter.go
- adjust to latest changes in golangci lint 1.58.2
-
> chore: Fix linting issues with 1.58.2

- config/busola/logpipeline_busola_extension_cm.yaml
- config/busola/metricpipeline_busola_extension_cm.yaml
- config/busola/telemetry_busola_extension_cm.yaml
- config/busola/tracepipeline_busola_extension_cm.yaml
- Unify Telemetry, LogPipeline, MetricPipeline, and TracePipeline CRs' descriptions to be consistent with all CR descriptions in Kyma dashboard
- https://github.com/kyma-project/kyma/issues/18321
> fix: Unify CRs' descriptions in Kyma dashboard

- hack/make/provision.mk
- hack/shoot_gcp.yaml
- Deprecate `kyma provision gardener`
- - https://github.com/kyma-project/kyma/issues/18674
/area cli
/kind chore
> chore: Deprecate kyma provision gardener

- .env
- hack/make/provision.mk
- export variables required by envsubst
- remove unused Gardener image version variable
- https://github.com/kyma-project/telemetry-manager/actions/runs/9186934788/job/25263559028
- https://github.com/kyma-project/telemetry-manager/pull/1083
- https://github.com/kyma-project/kyma/issues/18674
> chore: Fix gardener shot provisioning

- docs/user/integration/dynatrace/README.md
- docs/user/integration/dynatrace/exporter-values.yaml
- Restructered the metric section by outlining 3 different options
- Provided more detailed instructions for all 3 options
-
> docs: Enhance Dynatrace guide for metric scenario

- .env
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Update telemetry-manager image to 1.16.1
-
> chore: Update telemetry-manager image to 1.16.1

- .env
- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Update telemetry-manager image to 1.15.1
-
> chore: Update telemetry-manager image to 1.15.1

- test/integration/istio/metrics_self_monitor_outage_test.go
- test/integration/istio/traces_self_monitor_backpressure_test.go
- test/integration/istio/traces_self_monitor_outage_test.go
- dont check the buffer-is-full condition in the backpressure test, as it is also tested in the outage test
-
> fix: Stabilize flaky e2e self-monitoring tests

- .testcoverage.yml
After rewriting reconciler unit tests, we should make sure that test coverage does not drop
- Include reconcilers in the test coverage check
- Sort exceptions alphabetically
-
> chore: Include reconcilers in the test coverage check

- .github/workflows/pr-code-checks.yml
- hack/make/dependencies.mk
- Following the team agreement, we are removing the linter version check to avoid unnecessary disruptions. Instead, we will rely on Slack notifications to prompt updates for the linter and other tools.
-
> chore: Remove lint version check

- docs/contributor/releasing.md
- internal/otelcollector/config/metric/agent/processors_test.go
- internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
- internal/otelcollector/config/metric/agent/set_instrumention_scope.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
- internal/version/version.go
- main.go
- test/e2e/metrics_multi_pipeline_test.go
- test/testkit/matchers/metric/metric_matchers.go
- test/testkit/matchers/metric/metric_matchers_test.go
- Set module version in instrumentation scope for Prometheus metrics
- Log version after operator start
-  #1000
> feat: Set module version in instrumentation scope

- internal/otelcollector/config/metric/agent/processors_test.go
- internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
- internal/otelcollector/config/metric/agent/set_instrumention_scope.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
- Remove unnecessary check for scope name in transform processor
- #1134, , #1000
> chore: Eliminate unnecessary check in transform processor

- docs/contributor/arch/010-logging-flow-healthiness-status-api.md
- Add an explanation of why we have a special reason for LogPipelines only
- Remove the note since we are reflecting BufferFillingUp in a negative condition
-
> docs: Extend flow health ADR

- hack/load-tests/log-fluentbit-test-setup.yaml
- hack/load-tests/run-load-test.sh
- Reduce log generator instances from 20 to 10
- Fetch pod memory, cpu, and buffer metrics with `avg_over_time` for 20 minutes time frame
- Update input and output rates metric fetching with `rate` and 20 minutes time frame  
-
> fix: Log load test metric fetch 

- internal/reconciler/logpipeline/status.go
- internal/reconciler/metricpipeline/status.go
- internal/reconciler/tracepipeline/status.go
- Make the status conditions `TelemetryFlowHealthy` and `Pending`(a legacy condition) independent of the `ConfigurationGenerated` condition. Thus, in case that the order of setting the conditions is changed, the evaluation of the conditions will not be affected.
- #298
> chore: Make status conditions independent of each other

- Dockerfile
- main.go
- Update base image for manager build to newest debian release
- Update directory-size-exporter version
- https://github.com/kyma-project/telemetry-manager/pull/1169
> chore: Update base image for manager build to newest debian release

- README.md
- docs/contributor/installation.md
- docs/user/integration/jaeger/values.yaml
-  Removed outdated strategy links from README
- Fixed manual install instructions
- Fixed jaeger tutorial, the allInOne strategy requires to have a storage type configured
-
> docs: Removed outdated strategy links from README

- apis/telemetry/v1alpha1/tracepipeline_types.go
- apis/telemetry/v1beta1/tracepipeline_types.go
- config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
- docs/contributor/arch/001-otel-collector-metric-based-pipeline-status.md
- docs/contributor/pocs/otlp-logs.md
- docs/user/resources/04-tracepipeline.md
- Consistent spelling for “OTel” (see official acronym at https://opentelemetry.io/docs/specs/otel/#project-naming)
-
> chore: Fix spelling of OTel acronym

- .github/workflows/pr-loadtest.yml
- Fix wrong cluster name ci-traces-b, this conflicting with previous run
-
> fix: Wrong github action load test cluster name

- internal/tlscert/tls_cert_validator.go
- internal/tlscert/tls_cert_validator_test.go
- CA as optional TLS parameter + UTs
- Resolves #1192
> fix: CA as optional TLS parameter

- internal/selfmonitor/config/config_builder.go
- internal/selfmonitor/config/testdata/config.yaml
- Remove labeldrop statements from self-monitor's scrape config to fix false positive flow health conditions.
- #1187
> fix: Remove labeldrop from self-monitor scrape config

- .testcoverage.yml
- internal/reconciler/tracepipeline/reconciler.go
- internal/reconciler/tracepipeline/reconciler_test.go
- internal/reconciler/tracepipeline/stubs/gateway_resources_handler.go
- Add a TracePipeline reconciler unit test to ensure that the `DeleteResources(ctx context.Context, c client.Client, isIstioActive bool)` function is called when all TracePipelines are non-reconcilable
- #298
> test: Add TracePipeline reconciler unit test when all TracePipelines are non-reconcilable

- internal/reconciler/logpipeline/reconciler.go
- internal/resources/fluentbit/resources.go
- internal/resources/fluentbit/resources_test.go
- webhook/dryrun/file_writer.go
- Remove dead code for conditionally adding `@INCLUDE` statement for pipeline specific Fluent Bit sections
- #298 
- https://github.com/kyma-project/telemetry-manager/pull/1194
> chore: Cleanup Fluent Bit config generation

- config/busola/logpipeline_busola_extension_cm.yaml
- config/busola/metricpipeline_busola_extension_cm.yaml
- config/busola/telemetry_busola_extension_cm.yaml
- config/busola/tracepipeline_busola_extension_cm.yaml
- semantic change for highlights after moving to UI5
- https://github.com/kyma-project/busola/issues/3001
> fix: Highlights for badges

- docs/contributor/benchmarks/README.md
- hack/load-tests/run-load-test.sh
- main.go
- sec-scanners-config.yaml
- Update of self monitor to prometheus 2.53.0
- 2.53.0 is the next LTS release of prometheus (https://prometheus.io/docs/introduction/release-cycle/)
- updated to alpine 1.20 as well
- improved perf test metrics to be consistent with other queries and considering the maximums over the whole execution time
- https://github.com/kyma-project/third-party-images/pull/438
- https://github.com/kyma-project/telemetry-manager/actions/runs/9600191641/job/26475782779
> feat: Update of self monitor to prometheus 2.53.0

- internal/resources/selfmonitor/resources.go
- Mitigate the impact of the [issue](https://github.com/kubernetes/kubernetes/issues/122160) on self-monitor deployment, retention size configuration value decreased to 50MB to avoid configured volume exceeding the limit
-
> chore: Change self monitor retention size configuration from 80MB to 50MB

- hack/make/provision.mk
- With this [PR](https://github.com/kyma-project/telemetry-manager/pull/1220/files#diff-3f659f70fa78445803fb10dd7ee651fc36f09ba7015adef99281cece7114f02b) `kyma` dependecy has been removed. Remove it from deprovision-gardner target as well
-
> chore: Remove kyma dependency from Gardener deprovision

- sec-scanners-config.yaml
- Exclude test doubles from whitesource checks
-
> chore: Exclude test doubles from whitesource checks

- .github/workflows/tag-release.yml
- hack/release.sh
- Add numerical sorting based on major, minor, patch number to the tag list output from git. This helps in identifying the previous release based on the current one, enabling proper changelog generation with GoReleaser.
- Resolves #1213
> chore: Fix changelogs for non-sequential releases

- docs/contributor/pocs/assets/otel-log-agent-values.yaml
- docs/contributor/pocs/assets/otel-log-gateway-values.yaml
- internal/otelcollector/config/metric/agent/receivers.go
- internal/otelcollector/config/metric/agent/receivers_test.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
The ${env:ENV} syntax in otel-collector config does parse the value as yaml, which can be dangerous depending on the input. I removed the prefix everywhere to use plain ${ENV} which does not do any parsing.
- Changed all occurences to not use the env prefix
-
> chore: Do not use env prefix for env variables in otel config

- .github/workflows/pr-github-checks.yml
- internal/reconciler/telemetry/reconciler.go
- internal/resources/selfmonitor/resources.go
- internal/resources/selfmonitor/resources_test.go
- internal/selfmonitor/config/config_builder.go
- internal/selfmonitor/config/config_builder_test.go
- internal/selfmonitor/config/testdata/config.yaml
- Adjusted command args of prometheus to log in JSON
- Externalized constants which are re-used to assure the proper usage of them
-
> feat: Self-monitor logs in JSON format

- docs/user/integration/dynatrace/README.md
- Fix missing link in dynatrace integration guide
-
> docs: Fix missing link in dynatrace integration guide

- test/e2e/telemetry_logs_analysis_test.go
- test/testkit/suite/suite.go
- Refactored the log test to analyze all logs with one test setup
- Enabled the test (a wrong label avoided execution)
- Added more excludes for otel collector components
- Adjusted fluentbit verification to search for errors in the log body as it is not logging in json
- Added new test case for the self-monitor
-
> chore: Check for warnings/errors in telemetry-self-monitor

- .github/pull-request-template.md
- remove unnecessary checkbox in pr template
-
> chore: Update pr template

- controllers/telemetry/logparser_controller.go
- controllers/telemetry/logpipeline_controller.go
- internal/overrides/handler.go
- internal/overrides/handler_test.go
- internal/reconciler/logpipeline/reconciler.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/telemetry/reconciler.go
- internal/reconciler/tracepipeline/reconciler.go
- main.go
- Simplify overrides.Handler instantiation by decreasing the number of parameters passed into the constructor
- Makde default atomilLevel a singleton defined in the overrides pkg
- Sort constants in main.go
-
> chore: Simplify overrides handler

- .env
- config/manager/kustomization.yaml
- hack/load-tests/run-load-test.sh
- main.go
- sec-scanners-config.yaml
- test/testkit/mocks/backend/deployment.go
- Bump telemetry-manager image for releasing 1.20.0
- Bump kyma-otel-collector image version to 0.104.0-1.20.0
-
> chore: Bump images for releasing version 1.20.0

- hack/load-tests/run-load-test.sh
- main.go
- sec-scanners-config.yaml
- test/testkit/mocks/backend/deployment.go
- During development (main branch) we want to always use the latest image created from the main branch of the opentelementry-collector-components repository
-
> feat: Use latest kyma-otel-collector image on main branch

- Dockerfile
- apis/telemetry/v1alpha1/logpipeline_types.go
- apis/telemetry/v1beta1/logpipeline_types.go
- config/busola/logpipeline_busola_extension_cm.yaml
- config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
- config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
- docs/user/resources/02-logpipeline.md
- internal/fluentbit/config/builder/config_builder_test.go
- internal/fluentbit/config/builder/kubernetes_filter.go
- internal/fluentbit/config/builder/kubernetes_filter_test.go
- webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
- webhook/dryrun/testdata/given/logpipeline-1.yaml
- Added new attribute `keepRawBody` to the application input section of Logpipeline
- The default value of the new attribute is `true`
- If the `keepRawBody` is `false` and the original log content is JSON payload and parsing was successful the `log` attribute of the log record dropped.
- https://github.com/kyma-project/telemetry-manager/issues/551
> feat: Drop log body after record successfully parsed

- .github/dependabot.yml
- have dependabot create a single commit for all k8s related dependency bumps
- have dependabot create a single commit for all istio related dependency bumps
-
> chore: Group dependency bumps into single PR per project

- config/busola/logpipeline_busola_extension_cm.yaml
- config/busola/metricpipeline_busola_extension_cm.yaml
- config/busola/tracepipeline_busola_extension_cm.yaml
- For historical reasons the navigation node listening all the telemetry related resource types (LogPipeline,..) is under "Observability". This PR changes it to "Telemetry" as the relation to the actual module is much more obvious
-
> feat: Rename navigation node in kyma dashboard to "telemetry"

- config/manager/kustomization.yaml
- hack/provision-k3d.sh
- Revert mistakenly merged changes to kustomization.yaml and provision-k3d.sh
- Introduced in https://github.com/kyma-project/telemetry-manager/pull/1288
> chore: Revert kustomization.yaml and provision-k3d.sh

- .golangci.yaml
- internal/resources/otelcollector/agent.go
- internal/resources/otelcollector/agent_test.go
- internal/resources/otelcollector/core.go
- internal/resources/otelcollector/gateway.go
- internal/resources/otelcollector/gateway_test.go
- internal/resources/otelcollector/rbac.go
- internal/testutils/pod_builder.go
- Add new linter [unexported-return](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return) which will fail when an exported function or method returns a value of an un-exported type.
- Fixed the occurrences where the rule of this linter was not followed.
-
> chore: Add unexported-return linter

- test/integration/istio/metrics_self_monitor_outage_test.go
- test/testkit/mocks/telemetrygen/telemetrygen.go
- Fix flaky self-monitor-metic-outage e2e test
- BufferFillingUp tests fail occasionally for both metric and trace self-monitor outage tests, GatewayExporterDroppedData alert firing before GatewayExporterQueueAlmostFull alert. Data dropped from the queue before reaching 80% of the queue capacity, because some queued items reached the max retries limit of 6 minutes before the queue reached 80% of capacity.
-
> test: Flaky self-monitor metric outage tests

- config/development/kustomization.yaml
- config/rbac/role.yaml
- controllers/telemetry/metricpipeline_controller.go
- internal/reconciler/metricpipeline/reconciler.go
- internal/resources/otelcollector/rbac.go
- internal/resources/otelcollector/rbac_test.go
- main.go
- Add the required RBAC for the k8s cluster receiver from [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver#rbac)
- Add a flag to enable k8s cluster receiver
- Added option `k8s-cluster-receiver-allowed` under dev deployment
- https://github.com/kyma-project/telemetry-manager/issues/1184
> feat: Add required RBAC for k8s cluster receiver

- .github/workflows/skip-on-docu-paths.yml
- Add a workload that runs for docs-only PRs and satisfies the coding and e2e-test required checks
-
> chore: Unblock docs-only PRs

- .github/template/finalize-test/action.yaml
- .github/workflows/branch-integration.yml
- .github/workflows/pr-integration.yml
- .github/workflows/pr-lifecycle.yml
- hack/gardener-integration-test.sh
- to have it trackable what test cases were executed for a commit, junit reports are getting generated and uploaded to the actions
-
> chore: Collect JUnit reports as part of gingko executions

- .github/workflows/branch-integration.yml
- hack/deploy-istio.sh
- hack/wait-for-namespaces.sh
- Fixed naming of junit report for gardener integration job introduced by https://github.com/kyma-project/telemetry-manager/pull/1365
- Enhanced istio check by waiting for istiod to be ready, so that the istio webhooks are working at anytime when creating test resources
-
> chore: Fix gardener integration job

- .github/workflows/pr-github-checks.yml
This reverts commit 8cb7eeb73744d35fc37618e1944d192b1201100f.
- Revert [PR](https://github.com/kyma-project/telemetry-manager/pull/1344)
- As during the release we have to update the `kustomization` file so that the image name is in sync with the release branch name.
-
> chore: Revert "chore: Implement pr-prevent-kustomization GHA"

- hack/wait-for-namespaces.sh
- The step is executed at the end of the pipeline execution and then the cluster is deleted. So revert the change
-
> test: Revert the err check for namespace deletion

- .github/workflows/pr-lifecycle.yml
- hack scripts are not part of the product. So run the script from current branch from which PR has been created
-
> chore: Run hack script from the current branch from which PR has been created

- docs/user/integration/dynatrace/exporter-values.yaml
- There can be a case where attributes/resource attribute keys might have empty values. In such case these keys are dropped by the dynatrace backend (accepting the metric). There is warning in such a case which can cause confusion.
Unfortunately ottl does not support generic way of finding all the keys with values so currently hardcoding the keys which can have possible issue. 
- https://github.com/kyma-project/telemetry-manager/issues/1317
> docs: Improve  dynatrace config to drop empty attributes and resource attributes

- .github/workflows/build-image.yml
- hack/await_workflow.sh
- Revert Build-Image-Success job deletion, since `await_workflow.sh` depends on it
- Fixes https://github.com/kyma-project/telemetry-manager/pull/1439
> chore: Await build-image instead of Build-Image-Success job

- .env
- .github/workflows/branch-integration.yml
- Update all tooling to k8s 1.29
- Adjust integration tests to test for 1.29 and 1.30
-
> chore: Update to k8s 1.29

- config/rbac/role.yaml
- controllers/telemetry/metricpipeline_controller.go
- main.go
- Remove CRDs from MetricPipeline watched resources
- Remove RBAC annotations for CRDs
- Regenerate RBAC manifests
- With #1452, the istio status check implementation was changed to not search for CRDs anymore, but the metric pipeline still watches for CRDs, which is not useful anymore
> chore: Cleanup unused crd functions

- hack/await_workflow.sh
- Workflow script was not sleeping after outputting results, which continuously polled the GitHub API without any intervals and caused API rate limite errors
-
> chore: Fix workflow not sleeping after output results

- .github/pull-request-template.md
- Add a check for adjusting Busola in the PR template
-
> chore: Add a check for adjusting Busola in the PR template

- docs/contributor/arch/014-telemetry-self-monitor-storage.md
- internal/resources/selfmonitor/resources.go
- In some clusters, we observed Self Monitor local storage runs out of space, Self Monitor local storage size doubled to cover storage requirements in such cases.
-
> fix: Adjust Self Monitor storage size

- .github/workflows/pr-github-checks.yml
- As tide is disabled, introducing a "do not merge" label check
- https://github.com/kyma-project/test-infra/pull/12037
> chore: Introduce do not merge check

- internal/validators/endpoint/endpoint_validator.go
- internal/validators/endpoint/endpoint_validator_test.go
- Fix an untreated scenario in the endpoint validation logic (OTLP GRPC endpoint with path and port)
-
> fix: Endpoint validation with path and port scenario

- docs/user/04-metrics.md
- internal/otelcollector/config/metric/agent/config.go
- internal/otelcollector/config/metric/agent/receivers.go
- internal/otelcollector/config/metric/agent/receivers_test.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
- test/testkit/metrics/runtime/node.go
- enable working set and rss memory for the nodes
-
> feat: Enable all memory metrics for nodes

- .env
- config/manager/kustomization.yaml
- main.go
- sec-scanners-config.yaml
- Bump images to prepare for 1.25.0 release
-
> chore: Bump images to prepare for 1.25.0 release

- .github/workflows/branch-integration.yml
- .github/workflows/build-image.yml
- .github/workflows/pr-code-checks.yml
- .github/workflows/pr-docu-checks.yml
- .github/workflows/pr-integration.yml
- .github/workflows/pr-lifecycle.yml
- .github/workflows/sync-external-images.yml
- external-images.yaml
- introduce workflows to replace the discontinued image syncing functionality from test-infra
-
> feat: Add workflows for external image syncing

- docs/contributor/arch/003-integrate-prometheus-with-telemetry-manager-using-alerting.md
- Change deprecated link for otel-collector in Alerting ADR
- https://github.com/open-telemetry/opentelemetry-collector/pull/11483
> docs: Updated deprecated otel docs link

- .env
- config/manager/kustomization.yaml
- main.go
- sec-scanners-config.yaml
- Bump images for 1.26.0 release
-
> chore: Bump images for 1.26.0 release

- config/rbac/role.yaml
- main.go
- Operator container was printing the following log message:
```
{"level":"ERROR","timestamp":"2024-10-22T15:15:54Z","caller":"cache/reflector.go:158","message":"Unhandled Error","logger":"UnhandledError","error":"pkg/mod/k8s.io/client-go@v0.31.1/tools/
cache/reflector.go:243: Failed to watch *v1.CustomResourceDefinition: unknown (get customresourcedefinitions.apiextensions.k8s.io)"
```
Even though the `watch` permissions is not required, the operator is already granted `get` and `list` permissions, so adding `watch` to satisfy controller-runtime is fine.
-
> fix: Get rid of spammy RBAC log

- .env
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- main.go
- sec-scanners-config.yaml
- Cherry-picked: [fix: Get rid of spammy RBAC log (#1548)](https://github.com/kyma-project/telemetry-manager/commit/1afb87b4205d50d660f47b3b03b0d921c9a4e156)
- Bump images for the 1.26.1 version
-
> chore: Cherry pick RBAC errors and bump version to 1.26.1

- main.go
- sec-scanners-config.yaml
- Bump directory-size-exporter image to fix the rolling upgrade problem
- https://github.com/kyma-project/telemetry-manager/issues/1545
> chore: Bump directory-size-exporter image

- main.go
- Extract operator ports into constants to improve code glanceability
-
> chore: Extract operator ports into constants

- docs/user/04-metrics.md
- Improve the example for runtime resources metrics, so that some metrics which are not enabled by default are explicitly enabled in the example
-
> docs: Improve runtime resources metrics example

- test/e2e/telemetry_logs_analysis_test.go
- Revert the log analysis test for the manager container itself
- We agreed that this test is not meaningful and will lead to a huge flakiness
-
> chore: Revert telemetry manager log test

- internal/resources/fluentbit/resources.go
- Sometimes there are OOM in directory size exporter. Bump the memory limit to 50Mi
- Additionally add cpu requests as well
-
> fix: Bump memory limit for directory size exporter

- internal/resources/fluentbit/resources.go
- To avoid hitting CPU quota limits increase the cpu limit for directory size exporter to 100M
-
> fix: Bump CPU limit for the directory size exporter container

- .env
- config/manager/kustomization.yaml
- main.go
- sec-scanners-config.yaml
- Bump images for 1.28.0 release
-
> chore: Bump images for 1.28.0 release

- docs/user/02-logs.md
- docs/user/03-traces.md
- docs/user/04-metrics.md
- Replace Remedy with Solution
- https://github.com/kyma-project/community/pull/950
> docs: Replace Remedy with Solution

- hack/load-tests/log-fluentbit-test-setup.yaml
- hack/load-tests/metric-load-test-setup.yaml
- hack/load-tests/self-monitor-test-setup.yaml
- hack/load-tests/trace-load-test-setup.yaml
- The load generation was behaving different since last refactoring of the test suite with https://github.com/kyma-project/telemetry-manager/pull/1632
- Might be related by using wrong labels for node affinity settings, this PR fixes it
-
> chore: Fix perf test problems

- .env
- config/manager/kustomization.yaml
- main.go
- sec-scanners-config.yaml
- Bump the images for the release 1.29.0
-
> chore: Bump images for the release 1.29.0

- .github/workflows/branch-integration.yml
- K8s 1.31 is available in a supported mode on gardener -> start testing on it
- K8s 1.29 is not used anymore -> stop testing on it
-
> chore: Switch integration testing to k8s 1.31

- .env
- config/manager/kustomization.yaml
- hack/load-tests/metric-agent-test-setup.yaml
- internal/otelcollector/config/metric/agent/config.go
- internal/otelcollector/config/metric/agent/prometheus_receiver.go
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
- main.go
- sec-scanners-config.yaml
- Bump images for 1.29.1 patch release
- Cherry-pick "Optimize Prometheus scrape target discovery" https://github.com/kyma-project/telemetry-manager/pull/1663
-
> fix: Optimize Prometheus scrape target discovery and prepare images for 1.29.1 release

- .github/workflows/build-image.yml
- hack/await_image.sh
- Fix bad shell script in build-image create tag step
- Fix outdated variable name COMMIT_SHA in await_image.sh script
-
> chore: Fix build-image after introducing merge queue

- test/e2e/overrides_test.go
- Remove flaky test case, will be rewritten in a follow-up PR
-
> chore: Remove flaky telemetry override e2e test

- .env
- config/manager/kustomization.yaml
- internal/images/images.go
- main.go
- sec-scanners-config.yaml
- test/e2e/overrides_test.go
- Prepare images for 1.30.0 release
- Cherry-pick https://github.com/kyma-project/telemetry-manager/pull/1690 to address the flaky test that blocks the release. Since "Overrides" is an internal, non-user-facing feature, this change is acceptable.
-
> chore: Prepare images for 1.30.0 release

- .github/workflows/pr-lifecycle.yml
- Use new make target in upgrade test
-
> chore: Adjust upgrade test to new make targets

- .github/workflows/pr-release.yml
- check that .env file does not contain image references to the main branch
-
> chore: Prevent references to images from main on release-branch

- internal/tools/populateimages/main.go
- Fix the wrong path of `sec-scanner-config.yaml`
-
> chore: Fix wrong sec-scanner-config.yaml file path

- .github/workflows/branch-integration.yml
- Merge queue isn't available for rulesets with wildcard patterns, and our release branch rulesets uses the `release-*` name pattern
- Revert the change that branch-integration should run only in merge_group events for release branch
-
> chore: Revert running branch integration only on merge group

- internal/resources/otelcollector/agent_test.go
- internal/resources/selfmonitor/resources_test.go
- internal/resources/selfmonitor/testdata/self-monitor.yaml
- internal/utils/test/marshal.go
- Change self monitor unit tests to use golden files
- Refactor agent for it to be easier to add new tests (e.g. for log agent in the future)
- Change fluent bit unit tests to use golden files
- #1662
> chore: Refactor unit-tests to use golden files

- .github/template/prepare-test/action.yaml
- Wait for readiness probe to succeed which ensures that the webhook certs are generated and the webhooks are configured
-
> test: Fix flaky tests by really waiting for manager readiness

- test/e2e/telemetry_test.go
- This change did not help, so trying something else: https://github.com/kyma-project/telemetry-manager/pull/1699
-
> test: Fix flaky telemetry test (Pt. 2)

- docs/user/README.md
- docs/user/integration/README.md
- docs/user/integration/prometheus/values.yaml
- Removed unsupported flag from prometheus values yaml which caused a warning
- Added links to the overview pages to promote the new guides
-
> docs: Fixed prometheus guide and aded links to the overview pages

- renovate.json
- Enable renovate for the repo
- Enable a customManager to update the istio module dependency in the env file
- Disable all other managers for now
-
> chore: Add renovate for updating istio dependency

- .env
- docs/contributor/benchmarks/README.md
- internal/images/images.go
- sec-scanners-config.yaml
- Update fluentbit agent to 3.2.4
- https://github.com/kyma-project/telemetry-manager/pull/1780
- https://github.com/kyma-project/telemetry-manager/actions/runs/12925320510
> feat: Update fluentbit agent to 3.2.4

- internal/tools/populateimages/main.go
- sec-scanners-config.yaml
With recent tool naming change, we want to keep the same names in security-scanner-config
- Rename `protecode` to `bdba`
- Rename `whitesource` to `mend`
kyma/test-infra#491
> chore: Rename security-scanners-config fields

- .env
- .github/dependabot.yml
- Dockerfile
- docs/user/integration/sample-app/Dockerfile
- docs/user/integration/sample-app/go.mod
- go.mod
- internal/images/images.go
- internal/tools/go.mod
- renovate.json
- sec-scanners-config.yaml
- test/testkit/images.go
- Update to golang 1.23.6
- Enabled renovate for dockerfiles
- Update exporter image
- Updated telemetrygen
- Configured renovate for k3d update
-
> chore: Update to golang 1.23.6

- docs/contributor/development.md
- internal/reconciler/logpipeline/otel/reconciler.go
- internal/reconciler/logpipeline/otel/reconciler_test.go
- internal/reconciler/metricpipeline/reconciler_test.go
- test/e2e/logs_otlp_no_input_test.go
- Delete OTLP log agent resources when no longer needed
- Resolves https://github.com/kyma-project/telemetry-manager/issues/336
> fix: Delete OTLP log agent resources when no longer needed

- .github/workflows/pr-github-checks.yml
- we need to checkout the code so that it can read its configuration
-
> chore: checkout code to be accessible in github action

- test/e2e/logs_otlp_no_input_test.go
- test/e2e/metrics_no_input_test.go
- e2e tests "no input" should not be upgrade tests
-
> fix: e2e tests no input should not be upgrade tests

- .github/workflows/pr-github-checks.yml
> fix: reset forbidden github actions to allowed values

- internal/selfmonitor/webhook/handler.go
- internal/selfmonitor/webhook/handler_test.go
- use decoder to unmarshall json in non-greedy-way
- add test for huge request body
-
> chore: limit alerts payload size

- .github/workflows/build-image.yml
- .github/workflows/build-sample-app-image.yml
- .github/workflows/build-telemetry-self-monitor-image.yml
- due to changes on org level we need additional permissions for the tokens used in our image builder workflows
-
> chore: add additional permissions for image builder

- .github/workflows/pr-integration.yml
- .github/workflows/pr-upgrade.yml
- Exclude docs from integration test workflows
-
> chore: Exclude docs from integration test workflows

- .github/workflows/pr-github-checks.yml
- Use a version tag for the `tj-actions/changed-files` GHA, to avoid future compromise problems
- See: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised and https://github.com/tj-actions/changed-files/releases/tag/v46.0.1
> fix: Use version tag for tj-actions/changed-files

- .env
- config/manager/kustomization.yaml
- internal/images/images.go
- main.go
- sec-scanners-config.yaml
> chore: prepare images for 1.36.0 release

- .github/workflows/pr-github-checks.yml
- As agreed with the team, PR titles should conform to conventional commits (https://www.conventionalcommits.org/en/v1.0.0/) since it will be taken as a commit message of the squashed PR
-
> chore: ensure PR titel subject doesn't start with an uppercase character

- test/testkit/mocks/prommetricgen/metric_producer.go
-  Use latest sample-app in E2E tests
- Fix metric names to be compatible with the latest with the latest OTel SDK
-
> chore: use latest sample-app in E2E tests

- docs/user/integration/sample-app/deployment/deployment-prometheus.yaml
- docs/user/integration/sample-app/main.go
- internal/otelcollector/config/metric/agent/config.go
- internal/otelcollector/config/metric/agent/prometheus_receiver.go
- internal/otelcollector/config/metric/agent/testdata/config_compatibility_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
- internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
- add support for `prometheus.io/param_{name}: {value}` annotation for setting URL params when scarping
- update `sample-app` to record such requests, to be used by E2E tests in a follow-up PR
- https://github.com/kyma-project/telemetry-manager/issues/1938
> feat: add support for URL parameter annotations in scraping

- internal/tools/populateimages/main.go
- sec-scanners-config.yaml
- exclude sample-app and all docs from security scanning
-
> chore: exclude sample-app and all docs from security scanning

- .env
- config/manager/kustomization.yaml
- internal/images/images.go
- main.go
- sec-scanners-config.yaml
- Bump images version to 1.37.0
-
> chore: bump images version to 1.37.0

- internal/resources/common/pod_spec.go
- internal/resources/fluentbit/resources.go
- internal/resources/fluentbit/testdata/fluentbit.yaml
- internal/resources/otelcollector/agent.go
- internal/resources/otelcollector/testdata/log-agent.yaml
- internal/resources/otelcollector/testdata/metric-agent.yaml
- add tolerations to Fluent Bit, OTel Collector metric and log agents
- https://github.com/kyma-project/telemetry-manager/issues/1962
> feat: add tolerations to DaemonSet pod specs

- external-images.yaml
- Bump fluent-bit image in cache to version 4.0.0
-
> chore: update Fluent Bit image in cache to version 4.0.0

- external-images.yaml
- Bump fluent-bit image in cache to version 4.0.0
-
> chore: update Fluent Bit image in cache to version 4.0.1

- .env
- Makefile
- hack/make/provision.mk
- to avoid rate limiting from docker use synced k3s image
-
> chore: use synced image for k3s

- external-images.yaml
- update to newest k3d patch version in image cache
-
> chore: update to newest k3d patch version in image cache

- .github/template/finalize-test/action.yaml
- .github/template/setup-golang/action.yaml
- .github/workflows/branch-integration.yml
- .github/workflows/build-image.yml
- .github/workflows/build-sample-app-image.yml
- .github/workflows/build-telemetry-self-monitor-image.yml
- .github/workflows/periodic-github-checks.yml
- .github/workflows/pr-all-checks-passed.yml
- .github/workflows/pr-code-checks.yml
- .github/workflows/pr-docu-checks.yml
- .github/workflows/pr-github-checks.yml
- .github/workflows/pr-integration.yml
- .github/workflows/pr-loadtest.yml
- .github/workflows/pr-release.yml
- .github/workflows/pr-upgrade.yml
- .github/workflows/sync-external-images.yml
- .github/workflows/tag-release.yml
- CodeQL reports that default permissions are to corse-grained
- -> added most restrictive permissions for all jobs
- -> enabled more powerful permissions on the jobs directly
-
> chore: configure permissions for all gh actions

- .github/workflows/build-image.yml
- .github/workflows/build-sample-app-image.yml
- .github/workflows/build-telemetry-self-monitor-image.yml
- .github/workflows/pr-all-checks-passed.yml
- .github/workflows/pr-github-checks.yml
- .github/workflows/sync-external-images.yml
- Repeat default permission in overwrites as they are not additive
- https://github.com/kyma-project/telemetry-manager/pull/2114
> chore: fix permissions for all gh actions

- apis/telemetry/v1alpha1/logpipeline_types.go
- apis/telemetry/v1beta1/logpipeline_types.go
- config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
This PR ads verification to the LogPipeline to prevent cross-usage of fluentbit and otlp features. At the moment these fields are usable when having an OTLP output:
- spec.filters
- spec.values
- spec.files
- Adds CRD validation rules to prevent usage of otlp output in combination with "files", "variables" and "filters"
-
> fix: prevent cross-usage of fluentbit and otlp features

- internal/otelcollector/config/log/agent/receivers.go
- internal/otelcollector/config/log/agent/receivers_test.go
- internal/otelcollector/config/log/agent/testdata/config.yaml
- internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
- test/e2e/logs/fluentbit/keep_original_body_test.go
- test/e2e/logs/otel/application/basic_test.go
- test/e2e/logs/otel/application/multi_pipeline_namespace_selector_test.go
- test/e2e/logs/otel/application/payload_parser_test.go
- test/testkit/mocks/loggen/log_producer.go
The log body was moved to log.original always, even if it was not parsable
- In case log body is not JSON parsable, skip the whole operator chain as it is based on a parsed body
- Added more advanced test cases
- Removed unneeded operator outputs
-
> fix: move body only if it is json

- external-images.yaml
- update fluent-bit image in cache to 4.0.2
-
> chore: update fluent-bit image in cache to 4.0.2

- docs/contributor/arch/012b-leader-receiver-creator-as-extension.md
- Remove dead links to the repository, after `singleonreceivercreator` removed from the repository
- https://github.com/kyma-project/telemetry-manager/issues/2112
> chore: remove dead links after singleonreceivercreator removed from repo

- hack/gardener-integration-test.sh
- Avoid running tests for experimental features on gardener cluster, since we are deploying the non-experimental version on the gardener cluster in the branch integration job
-
> chore: avoid running tests for experimental features on gardener cluster

- docs/user/integration/sample-app/setup.go
The otel bump on the sample-app (https://github.com/kyma-project/telemetry-manager/pull/2235) caused that the sample-app could not startup anymore as the schemaUrl send with the data is not aligned anymore with the sdk version.
Instead of maintaining the schemaUrl with every otel bump, I removed the url from the sample
- removed schemaUrl from the sample
-
> docs: remove schemaUrl from sample-app

- docs/user/integration/sample-app/setup.go
- The sample-app started to enrich metric names expoted via prometheus with units. Do keep naming stable I explicitly configured the "withoutUnit" option
-
> docs: sample-app: do not have units in the exported prometheus metrics

- .github/workflows/pr-integration.yml
- test/e2e-migrated/logs/shared/self_monitor_healthy_test.go
- test/e2e-migrated/metrics/kyma_input_test.go
- test/e2e-migrated/metrics/self_monitor_healthy_test.go
- test/e2e-migrated/traces/self_monitor_healthy_test.go
- test/e2e/misc/overrides_test.go
- test/e2e/misc/telemetry_logs_analysis_test.go
- test/integration/istio/access_logs_otlp_test.go
- test/integration/istio/access_logs_test.go
- test/integration/istio/logs_agent_self_monitor_backpressure_test.go
- test/integration/istio/logs_agent_self_monitor_outage_test.go
- test/integration/istio/logs_fluentbit_self_monitor_backpressure_test.go
- test/integration/istio/logs_fluentbit_self_monitor_outage_test.go
- test/integration/istio/logs_gateway_self_monitor_backpressure_test.go
- test/integration/istio/logs_gateway_self_monitor_outage_test.go
- test/integration/istio/metrics_istio_envoy_multi_pipeline_test.go
- test/integration/istio/metrics_istio_input_envoy_metrics_test.go
- test/integration/istio/metrics_istio_input_test.go
- test/integration/istio/metrics_otlp_input_test.go
- test/integration/istio/metrics_prometheus_input_test.go
- test/integration/istio/metrics_self_monitor_backpressure_test.go
- test/integration/istio/metrics_self_monitor_outage_test.go
- test/integration/istio/traces_self_monitor_backpressure_test.go
- test/integration/istio/traces_self_monitor_outage_test.go
- test/integration/istio/traces_test.go
- test/testkit/assert/logs.go
- test/testkit/assert/metrics.go
- test/testkit/assert/telemetry.go
- test/testkit/assert/traces.go
…ng backend reachability
- Ensure the BackendReachable helper function is used everywhere for checking backend reachability, instead of just checking the deployment readiness
- Ensure consistency between selfmonitor e2e tests
-
> fix: assert backend reachability using helper function everywhere

- docs/user/integration/prometheus/values.yaml
- In the kube-prometheus-stack the OTLP support was added which collides with the existent way of configuration: https://github.com/prometheus-community/helm-charts/commit/e7f003930887d042176f066c21c00e49a73fd783
-
> docs: update prometheus example to upstream helm changes

- dependencies/populateimages/main.go
- sec-scanners-config.yaml
- the scanner config is not required for experimental releases. Listing the image there will lead to duplicated triaging of the same image
-
> chore: remove experimental image from scanner config

- apis/telemetry/v1alpha1/logpipeline_conversion.go
- apis/telemetry/v1alpha1/logpipeline_conversion_test.go
- Add TransformSpec conversion to the conversion webhook, which was forgotten when implementing https://github.com/kyma-project/telemetry-manager/issues/2349
-
> fix: conversion of LogPipelines

- external-images.yaml
- bump k3d version in image cache
-
> chore: bump k3d version in image cache

- external-images.yaml
- fixed sha used in https://github.com/kyma-project/telemetry-manager/pull/2460/files
- added next version for compatibility tests
-
> chore: update k3d image in cache

- docs/user/integration/loki/README.md
- the integration guide was migrated wrongly to the otlp approach, the path need to list the /v1/logs suffix as well
-
> docs: fix path in loki integration guide

- apis/telemetry/v1alpha1/shared_types.go
- apis/telemetry/v1beta1/shared_types.go
- docs/user/02-logs.md
- docs/user/03-traces.md
- docs/user/04-metrics.md
- docs/user/logs.md
- docs/user/resources/02-logpipeline.md
- docs/user/resources/04-tracepipeline.md
- docs/user/resources/05-metricpipeline.md
- helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_logpipelines.yaml
- helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_metricpipelines.yaml
- helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_tracepipelines.yaml
- helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_logpipelines.yaml
- helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_metricpipelines.yaml
- helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_tracepipelines.yaml
- fixed bad formatted md not valid in Vitepress (markdown-it)
- https://github.com/kyma-project/kyma/pull/18817
> docs: fixed bad formatted md not valid in Vitepress (markdown-it)

- internal/reconciler/metricpipeline/reconciler.go
- internal/reconciler/metricpipeline/reconciler_test.go
- Fix metricpipeline reconciliation loop agent deployment, where the agent does not get deployed if there's a broken metricpipeline deployed first.
-
> fix: metricpipeline reconciliation loop agent deployment

- .github/workflows/pr-loadtest.yml
After the upgrade of the https://github.com/actions/download-artifact/releases/tag/v5.0.0, the download path changed for single file downloads.
See the problem here: https://github.com/kyma-project/telemetry-manager/actions/runs/18092500102/job/51483365965
versus https://github.com/kyma-project/telemetry-manager/actions/runs/17967349590/job/51112854465
- Adjusted the download config to have a fixed output folder
- Use the merge-multiple option to have same behaviour for single and multiple downloads
-
> chore: fix perf result download in load test setup

- .env
- helm/Chart.yaml
- helm/charts/default/Chart.yaml
- helm/charts/experimental/Chart.yaml
- helm/values.yaml
- sec-scanners-config.yaml
- test/testkit/images.go
- chore release telemetry manager 1.49.0
-
> chore: release telemetry manage release 1.49.0
