Dockerfile
main.go

- updated fluentbit to be streamlined with related helm chart in kyma
- updated to latest golang image
- updated otel-collector to 0.71.0
https://github.com/kyma-project/third-party-images/pull/312

update Dockerfile to latest fluentbit, otel-collector and golang image

---

controller/logpipeline/controller.go
controller/logpipeline/controller_test.go

- Expose file system buffer size limit via metric

Expose File System Buffer limit as metric

---

main.go

Was accidentally removed by https://github.com/kyma-project/kyma/pull/16881
- Re-add pprof endpoint

Re-add pprof endpoint

---

Makefile
config/rbac/role.yaml
internal/kubernetes/utils.go
internal/resources/webhook/resources.go
internal/setup/webhook.go
internal/setup/webhook_test.go
main.go

- Generate web hook certificate by operator
- Generate ValidatingWebhookConfiguration by operator
- Remove obsolete make targets

Generate webhook configuration by operator

---

controller/logpipeline/controller.go
controller/tracepipeline/controller.go
controller/tracepipeline/controller_test.go
controller/tracepipeline/suite_test.go
internal/resources/common/resources.go
internal/resources/common/resources_test.go
internal/resources/logpipeline/resources.go
internal/resources/logpipeline/resources_test.go
main.go

- Add Otel collector RBAC creation to operator
https://github.com/kyma-project/kyma/issues/16909

Add otel collector RBAC creation

---

.golangci.yaml
controller/logpipeline/controller_test.go

- Enable [ginkgolinter](https://github.com/nunnatsa/ginkgolinter), which enforces several patterns of using ginkgo and gomega. The linter is recommended by ginkgo maintainers https://onsi.github.io/ginkgo/#the-ginkgolinter
- Fix a few gomega assertions

Add ginkgo linter

---

main.go

- update otel-collector to 0.72.0
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/315

update otel-collector to 0.72.0

---

CODEOWNERS
milv.config.yaml

- milv config for governance job added
https://github.com/kyma-project/kyma/issues/16745

Add governance job milv config

---

webhook/logpipeline/webhook_suite_test.go

Sleep statement increases the test runtime significantly and does not have an obvious use.
- Remove sleep statement from webhook test

Remove sleep statement from webhook test

---

Makefile
go.mod
hack/provision-test-env.sh
test/e2e/manager_test.go
test/e2e/suite_test.go

Add end-to-end tests to validate operator deployment.
- Add end-to-end tests
https://github.com/kyma-project/kyma/issues/16909

Add end-to-end tests

---

README.md

Unified spelling of Telemetry Manager according to [style and terminology](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/02-style-and-terminology.md#title-case) guide
- Fixed spelling of Telemetry Manager in README

Fixed spelling of Telemetry Manager in README

---

Makefile

- Add bin directory to PATH during the k3d installation to make the installer successful
https://github.com/kyma-project/kyma/issues/16909

Fix k3d installation

---

.golangci.yaml
internal/kubernetes/utils.go
webhook/logpipeline/validation/mocks/variables_validator.go
webhook/logpipeline/validation/variable_validator.go
webhook/logpipeline/validation/variable_validator_test.go
webhook/logpipeline/webhook.go

- Add `stylecheck` linter, which is a replacement for `golint`
- Fix error message
- Fix unused param
- Remove unneeded import alias

Add stylecheck linter

---

Dockerfile
config/samples/http-mockserver.yaml
controllers/telemetry/tracepipeline_controller_test.go
main.go

- updated used fluentbit image to latest golang version
- updated otel-collector to 0.73.0 and to newest golang version
- ...
https://github.com/kyma-project/third-party-images/pull/318

updated otel-collector and fluentbit version

---

Dockerfile
config/samples/http-mockserver.yaml
main.go

- update to fluentbit 2.0.10
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/320

update to fluentbit 2.0.10

---

Makefile

- Recently the `Build Dependency` make targets failed sometimes because a binary is already present in the local `bin` directory.
- Since this is quite annoying, I checked whether our Makefile is outdated and found some updates to those make targets:  
1. There is now an if section checking if the version is outdated: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L142-L145. This is not the reason for the failing make targets but I anyway changed it because it is handy.
```shell
@if test -x $(LOCALBIN)/kustomize && ! $(LOCALBIN)/kustomize version | grep -q $(KUSTOMIZE_VERSION); then \
echo "$(LOCALBIN)/kustomize version is not expected $(KUSTOMIZE_VERSION). Removing it before installing."; \
rm …
```

Update Makefile 'Build Dependency' targets

---

apis/telemetry/v1alpha1/logpipeline_validation.go
controllers/operator/telemetry_controller_test.go
controllers/telemetry/metricpipeline_controller_test.go
controllers/telemetry/tracepipeline_controller_test.go
internal/kubernetes/utils.go
internal/reconciler/telemetry/reconciler.go
webhook/logpipeline/webhook_suite_test.go

- Fix linting errors that were introduced by golangci-lint update

Fix linting errors

---

test/e2e/tracing_test.go

- Change the test to use secret from a different namespace other than `kyma-system` to check RBAC for telemetry manager

Improve tracing tests by using secret

---

Makefile
config/manager/kustomization.yaml

- Update default image in Makefile

Update default image in Makefile

---

Makefile
config/manager/kustomization.yaml

- Update default image to support namespace flag
https://github.com/kyma-project/kyma/issues/17195

Update default image to support namespace flag

---

internal/kubernetes/utils.go
internal/reconciler/logpipeline/reconciler.go

- Move Fluent Bit daemon set deletion code to logpipeline package since it is nowhere else used

Refactor Fluent Bit deletion

---

internal/reconciler/metricpipeline/config_builder.go
internal/reconciler/metricpipeline/config_builder_test.go

- Use following config values
| Property                                          | Value |
| ------------------------------------------------- | ----- |
| `processor.batch.timeout`                         | 10s   |
| `processor.memory_limiter.check_interval`         | 1s    |
| `processor.memory_limiter.limit_percentage`       | 75    |
| `processor.memory_limiter.spike_limit_percentage` | 10    |
| `processor.batch.send_batch_size`                 | 1024  |
| `processor.batch.send_batch_max_size`             | 0     |
| `exporter.otlp.sending_queue.queue-size`          | 512   |
https://github.com/kyma-project/kyma/issues/17069

Hardened configuration values for metrics gateway

---

main.go

- Update Otel collector to 0.74.0

Update Otel collector to 0.74.0

---

main.go

Set telemetry namespace to default to allow executing the manager without any CLI flags.
- Set telemetry namespace to default

Set telemetry namespace to default

---

Dockerfile
config/samples/http-mockserver.yaml

- update to fluentbit 2.0.11
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/326

update to fluentbit 2.0.11

---

config/manager/kustomization.yaml
test/e2e/testkit/mocks/traces/external_backend_service.go
test/e2e/testkit/otlp/traces/traces.go
test/e2e/testkit/otlp/traces_service.go
test/e2e/testkit/port_registry.go
test/e2e/tracing_test.go

- Fix variable name discrepancies in tracing test
- Add an utility to create a trace data sender

Fix variable name discrepancies in tracing test

---

Dockerfile
config/samples/http-mockserver.yaml
main.go

- update to otel-collector 0.75.0
- update fluentbit to golang 1.20.3
- ...
https://github.tools.sap/kyma/security-scans-pipelines/pull/121

update to otel-collector 0.75.0, update fluentbit to golang 1.20.3

---

controllers/telemetry/logpipeline_controller_test.go

- Replaced redundant generation comparison in logpipeline controller test

Flaky logpipeline controller test fix

---

Makefile
sec-scanners-config.yaml

- For the initial module release `0.1.0`, bump the the operator image and module version

Release 0.1.0

---

main.go

- Update Golang to 1.20.4
- Update Prometheus Client

Bump directory-size-exporter

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- bump images and module version

Release 0.2.0

---

controllers/telemetry/metricpipeline_controller_test.go
controllers/telemetry/otel_test_helpers.go
controllers/telemetry/tracepipeline_controller_test.go
internal/otelcollector/config/builder/config_builder.go
internal/otelcollector/config/builder/config_builder_test.go
internal/otelcollector/config/builder/env_vars.go
internal/reconciler/metricpipeline/config_builder.go
internal/reconciler/metricpipeline/config_builder_test.go
internal/reconciler/metricpipeline/reconciler.go
internal/reconciler/tracepipeline/config_builder.go
internal/reconciler/tracepipeline/config_builder_test.go
internal/reconciler/tracepipeline/reconciler.go
main.go

- Support multiple TracePipelines
- Support multiple MetricPipelines
https://github.com/kyma-project/kyma/issues/17234

Add support for multiple TracePipelines and MetricPipelines

---

main.go
sec-scanners-config.yaml

- update to otel-collector 0.77.0
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/343

update to otel-collector 0.77.0

---

Dockerfile
config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml

- update to fluent-bit 2.1.2
- ...
- ...
https://github.com/kyma-project/third-party-images/pull/344

update to fluent-bit 2.1.2

---

config.yaml

- Delete `config.yaml` file, since it is useless now

Delete config file

---

go.mod
go.sum

Reverts kyma-project/telemetry-manager#178

Revert "Bump github.com/onsi/gomega from 1.27.6 to 1.27.7"

---

config/manager/kustomization.yaml
config/manager/manager.yaml
config/manager/priority_class.yaml
config/manager/priority_class_high.yaml
controllers/telemetry/logpipeline_controller_test.go
controllers/telemetry/metricpipeline_controller_test.go
controllers/telemetry/tracepipeline_controller_test.go
main.go
test/e2e/logging_test.go
test/e2e/manager_test.go
test/e2e/testkit/kyma/telemetry/log/pipeline.go

- Introduce priority class for daemonsets
- Include tests for the priority
- Include tests for logs
https://github.com/kyma-project/kyma/issues/17157

Include priority class

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump images and module version for release 0.4.0

Release 0.4.0

---

internal/resources/fluentbit/resources.go
internal/resources/fluentbit/resources_test.go

- Make `/var/log` read-only
- Remove `/var/lib/docker/containers`

Clean up Fluent Bit volume mounts

---

main.go

- Declare a new error instead of overriding the existing one

Fix race condition

---

internal/resources/fluentbit/resources.go

- Exclude fluent-bit container from log collection
https://github.com/kyma-project/kyma/issues/17611

Remove Fluent Bit from log collection

---

Dockerfile
config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml
test/e2e/testkit/mocks/backend_deployment.go

- updated fluentbit image to use newest golang
- updated otel-collector to 0.79.0 and using newest golang version
- ...
https://github.com/kyma-project/third-party-images/pull/348

update images to use newest golang and otel-collector version

---

Makefile

Version number was not configured
- adjusted version number to reflect the release
- ...
- ...

adjusted version number

---

docs/user/README.md
docs/user/assets/general-components.drawio.svg
docs/user/assets/general-stages.drawio.svg
docs/user/assets/manager-lifecycle.drawio.svg
docs/user/assets/tracing-intro.drawio.svg

- Support dark mode for diagrams in documentation
- Small fix in main readme
- ...

Support dark mode for diagrams in documentation

---

sec-scanners-config.yaml

- Fix Whitesource exclude list in the security configuration

Fix Whitesource exclude list

---

Makefile

upgrade envtest k8s version to 1.26.5

---

.gitignore
Makefile
config/manager/kustomization.yaml

- Generate JUnit XML output for e2e tests

Generate JUnit XML output for e2e tests

---

Makefile

- envtest does not support kubernetes v1.26.5
- this PR sets the version to v1.26.1

use envtest v1.26.1 instead of v1.26.5

---

Makefile
hack/upgrade-test.sh
test/e2e/metrics_test.go
test/e2e/tracing_test.go

- Creates a make target for the upgrade test.
- Marks a subset of the E2E test suite as upgrade tests.
#213

Upgrade test

---

docs/user/02-logs.md

Apply changes to docs from https://github.com/kyma-project/kyma/pull/17783 also to new telemetry docs.
- Update docs for Fluent Bit retry limit
https://github.com/kyma-project/kyma/issues/17662

Update docs for Fluent Bit retry limit

---

config/manager/manager.yaml

Set log level for telemetry module to existing default

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump images and module version for release 0.6.0

Release 0.6.0

---

docs/contributor/testing.md

- Extends the document with procedures that impose SAP FC-1 (Source Code Quality), FC-2 (Testing of new functionality) and FC-3 (Testing of existing functionality) quality standards.
—

Adjusts the testing strategy document to adhere to typical quality standards

---

main.go
sec-scanners-config.yaml
test/e2e/testkit/mocks/backend_deployment.go

- Update OpenTelemetry Collector to 0.81.0

Update OpenTelemetry Collector to 0.81.0

---

apis/telemetry/v1alpha1/logpipeline_types.go
config/busola/logpipeline_busola_extension_cm.yaml
config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
docs/user/03-traces.md
docs/user/resources/02-logpipeline.md
webhook/logpipeline/webhook.go

- Fix broken links after removal of the `main-areas` section
- https://github.com/kyma-project/kyma/issues/17805

Fix broken links 

---

test/e2e/logging_test.go
test/e2e/metrics_test.go
test/e2e/suite_test.go
test/e2e/telemetry_test.go
test/e2e/testkit/k8s/label_opts.go
test/e2e/testkit/k8s/label_opts_test.go
test/e2e/testkit/k8s/objects.go
test/e2e/testkit/k8s/telemetry.go
test/e2e/testkit/kyma/telemetry/metric/pipeline.go
test/e2e/testkit/kyma/telemetry/trace/pipeline.go
test/e2e/tracing_test.go

- Added versioning for the pipelines under test
- Fixes bugs with persistent resources
Implements #236

Testing pipelines versioning

---

config/rbac/role.yaml
controllers/operator/telemetry_controller.go
main.go

- telemetry operator needs to create/patch events
- Remove duplicate annotation for rbac
Avoid following error
```
'events is forbidden: User \"system:serviceaccount:kyma-system:telemetry-operator\" cannot create resource \"events\" in API group \"\" in the namespace \"default\"' (will not retry!)
```

Add role to create/patch events

---

.github/pull-request-template.md

Refines the PR-template with the testability aspects.

---

docs/user/_sidebar.md

- add sidebar for navigation in the upcoming website engine
(the sidebar will be used to render it like here for [BTP Operator](https://kyma-docs.netlify.app//?basePath=https://raw.githubusercontent.com/kyma-project/btp-manager/main/&homepage=docs/user/README.md&sidebar=true&loadSidebar=docs/user/_sidebar.md&browser-tab-title=BTP%20Operator%20Documentation#/docs/user/README) (currently accessed from https://kyma-project.io/docs/kyma/main#kyma-modules))

add sidebar

---

docs/user/01-manager.md
docs/user/02-logs.md
docs/user/03-traces.md
docs/user/README.md

- replace relative links
Closes:
https://github.com/kyma-project/telemetry-manager/issues/271

replace relative links

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump images and module version for 0.7.0 release
Closes:

Release 0.7.0

---

Dockerfile
config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml

- Update Fluent Bit to 2.1.7
https://github.com/kyma-project/third-party-images/pull/365

Update Fluent Bit to 2.1.7 & golang to 1.20.6

---

docs/user/03-traces.md

- fix the rendering issues detected by @hisarbalik (https://github.com/kyma-project/telemetry-manager/issues/271#issuecomment-1644997052)
Closes:
https://github.com/kyma-project/telemetry-manager/issues/271

fix rendering issues

---

.golangci.yaml

Turns off the dupl linter verifications for the "_test.go" files.
Closes:
- an action item from the team architecture discussion meeting.
Irrelevant.
Irrelevant.
Not touched.

Disable the dupl linter verifications for the "_test.go" files.

---

.github/workflows/markdown-link-check.yml
.mlc.config.json
README.md
docs/contributor/governance.md

Adds a GitHub Action for the Markdown Link checker.
- Creates a GitHub Actions workflow using the [Markdown Link Check](https://github.com/marketplace/actions/markdown-link-check)
Closes:
Irrelevant
Irrelevant
Not touched

Markdown link checker

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump Images and modules to 0.8.0
- Also bump directory size exporter to latest version
Closes:

Release 0.8.0

---

.github/pull-request-template.md

Adds a link to the [Effective Go](https://go.dev/doc/effective_go#formatting) as a touchstone code style guide.
Closes:
- Action item from the team retrospective.
Irrelevant.
Irrelevant
Not touched.

Adds a link to the code style guideline.

---

README.md

- add a status badge
Closes:
n/a
n/a
n/a

add status badge to Telemetry README

---

hack/deploy-istio.sh
test/integration/istio_access_logs_test.go
test/testkit/k8s/namespace.go

Move namespace creation for sample app from setup script to test execution.
- Create namespace in Go code
Closes:
Related issues: preparation for https://github.com/kyma-project/telemetry-manager/issues/317

Refactor Istio access logs test

---

README.md

- Ensure that the mandatory sections (according to OSPO) exist
Closes:

Ensure mandatory README sections

---

docs/user/_sidebar.md

remove sidebar link

---

Makefile
internal/resources/fluentbit/resources.go
internal/resources/fluentbit/resources_test.go
test/e2e/logging_fluentbit_metrics_test.go
test/e2e/logging_parser_test.go

- Revert changes from https://github.com/kyma-project/telemetry-manager/pull/262
[New fluentbit metric exposure is not following prometheus specification leading to failed scrapes for other vendors#17976](https://github.com/kyma-project/kyma/issues/17976)
Closes:

Revert fluent-bit metric exposure

---

internal/otelcollector/config/metric/agent/config_builder_test.go
internal/otelcollector/config/metric/agent/receivers.go

- Increase default scrape interval for workloads and istio to 30 sec. 
https://github.com/kyma-project/telemetry-manager/issues/337
Closes:

Increase default metric scrape interval to 30 sec

---

.goreleaser.yaml
docs/contributor/releasing.md

This pull request amends the release process by addressing the bug in the changelog containing features from previous releases.
- Amendments to the release process:
- The main branch incorporates commits that bump the dependent containers.
- The release tags point to the commit in the release branches and the corresponding commits in the main branch.
- GitHub Release's changelog features grouping:
- `Test suites` section aggregates all changes containing a `test` word.
- `Documentation` section aggregates all changes containing `docs` or `document` word fragments. 
- `Features` section contains the rest of the changes.
Closes:
#287 
Release process on an imported repo …

Release amendments and GitHub Release changelog improvements

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump module version and images in preparation for release 0.9.0
Closes:

Bump module version and images for release 0.9.0

---

Dockerfile
config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml
test/testkit/mocks/backend_deployment.go

- update to otel-collector to 0.03.0
- update fluentbit to 2.1.8
- update to latest directory-size-exporter
https://github.com/kyma-project/third-party-images/pull/379
https://github.com/kyma-project/directory-size-exporter/pull/25
Closes:

update otel-collector, fluent-bit and directory-size-exporter

---

docs/contributor/releasing.md

Manageing the Github Milestones is not covered in the current release process
- added points to close old milestone and start a new one
- fixed intendations in existing sections
- 
Closes:

added milestone management to the release process

---

milv.config.yaml

- Removes the unused govenance job config
Closes:
Irrelevant
Irrelevant
Irrelevant

chore: Remove the MILV config file

---

Makefile
hack/deploy-istio.sh
test/integration/istio/istio_tracing_test.go
test/integration/istio/suite_test.go
test/testkit/k8s/verifiers/pod.go
test/testkit/matchers/trace_matchers.go
test/testkit/matchers/trace_matchers_test.go

Add Istio tracing test that validates the arrival of Istio sidecar spans in the trace backend. The test will be extended in a follow-up PR to also validate the connection between Istio- and custom-spans.
- Add Istio tracing integration test
Closes:
Related issues: https://github.com/kyma-project/telemetry-manager/issues/317

test: Add Istio tracing integration test

---

config/busola/logparser_busola_extension_cm.yaml
config/busola/logpipeline_busola_extension_cm.yaml
config/busola/telemetry_busola_extension_cm.yaml
config/busola/tracepipeline_busola_extension_cm.yaml

- busola extensions used links to already removed docu, updated to the new location
Closes:

fix: Broken docu links in busola extensions

---

config/busola/telemetry_busola_extension_cm.yaml

- After the moduleTemplate got namespaced scoped, it makes no sense to keep it under a separate navigation node in kyma-system namespace. So I aligned naming and location with the other modules
Closes:

fix: Corrected navigation of module in busola

---

apis/telemetry/v1alpha1/logpipeline_types.go
config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
docs/contributor/installation.md
docs/user/resources/02-logpipeline.md

fix: Broken doc links

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump Images and modules to 0.8.0
Closes:

chore: Release 0.10.0

---

sec-scanners-config.yaml

- Align `module-name` in the `sec-scanners-config.yaml` with the value used in the `operator.kyma-project.io/module-name` label in the module template.
Closes:

chore: Update module-name in sec-scanners-config.yaml

---

internal/otelcollector/config/metric/agent/receivers.go
internal/otelcollector/config/metric/agent/relabel_configs.go
internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml

- Fix a bug resulting in the target-dropping mechanism not working properly if `prometheus.io/scheme` annotation is not set. This fix ensures that the target dropping functionality works as intended, regardless of the annotation's configuration
https://github.com/kyma-project/telemetry-manager/issues/349

fix: Relabel configs that drop if scheme is HTTP/HTTPS

---

test/integration/istio/istio_tracing_test.go
test/testkit/matchers/trace_matchers.go
test/testkit/mocks/metricproducer/metric_producer.go

- Add e2e test for istio-proxy trace, test ensure istio-proxy traces are collected with telemetry trace collector
Closes:
https://github.com/kyma-project/telemetry-manager/issues/317

test: Check for custom spans in Istio tracing test

---

internal/reconciler/metricpipeline/reconciler.go
internal/reconciler/tracepipeline/reconciler.go

- Currently, when there are no deployable pipelines available, an error is raised and logged. However, this situation is expected and not an actual error. This PR addresses this by introducing a silent reconciliation skip in such cases, preventing the generation of errors. Instead, it logs a debug message to maintain clarity in the logs.
- Unified logging in the affected files
Irrelevant
Irrelevant

fix: Do not fail reconciliation if no deployable pipelines

---

apis/telemetry/v1alpha1/logpipeline_types.go
apis/telemetry/v1alpha1/metricpipeline_types.go
apis/telemetry/v1alpha1/shared_types.go
apis/telemetry/v1alpha1/tracepipeline_types.go
config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
config/development/telemetry.kyma-project.io_metricpipelines.yaml
docs/user/resources/01-telemetry.md
docs/user/resources/02-logpipeline.md
docs/user/resources/04-tracepipeline.md
docs/user/resources/05-metricpipeline.md

- added missing CRDa ttribute descriptions
- fixed examples for CRDs
Closes:

feat: Extend the descriptions of manifests

---

Makefile

- bump envtest k8s version to 1.27,1

chore: bump envtest k8s version to 1.27.1

---

Makefile
config/manager/kustomization.yaml
main.go
module_config.yaml
sec-scanners-config.yaml

- Bump images and module version for 1.0.0 release
Closes:

chore: Bump images and module version for 1.0.0 release

---

internal/secretref/secret_ref.go

- Dummy commit to check squashed commit messages
Irrelevant
Irrelevant
Irrelevant
Irrelevant

chore: Fix logs in secretref package

---

internal/kubernetes/utils.go
internal/kubernetes/utils_test.go

- Add `istio-operator.kyma-project.io/restartedAt` to the list of Pod annotations we preserve while reconciling DaemonSets and Deployments 
Closes:
https://github.com/kyma-project/telemetry-manager/issues/379

feat: Preserve restartedAt annotation

---

Dockerfile
config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml
test/testkit/mocks/backend/deployment.go

- update to fluentbit 2.1.9
- update to otel-collector 0.85.0
Additional manual tests are performed verifying resource footprint and throupghput KPIs. Also no warn/error logs appeared
Closes:
https://github.com/kyma-project/third-party-images/pull/382

feat: Update to fluentbit 2.1.9 and otel-collector 0.85.0

---

main.go

- Clone objects that are used in go routine for webhook setup
Closes:

fix: Potential race condition during webhook setup

---

docs/contributor/performance-tests/metrics/metrics.md

- Telemetry manager metric agent performance test and documentation of result
- Conclusion for reference implementation
Closes:
https://github.com/kyma-project/telemetry-manager/issues/375

docs: Perf tests updates for the metric agent 

---

config/development/kustomization.yaml
config/development/metricpipeline_busola_extension_cm.yaml
config/manager/kustomization.yaml
docs/user/resources/05-metricpipeline.md

- adds a new dashboard view for MetricPipeline
- adds missing TLS sections for TracePipeline
- dropped invalid attributes from the config
Closes:

feat: Dashboard view for MetricPipeline

---

main.go
sec-scanners-config.yaml
test/testkit/mocks/backend/deployment.go

- Update OpenTelemetry Collector to 0.86.0
Closes:

chore: Update OpenTelemetry Collector to 0.86.0

---

internal/otelcollector/config/config.go
internal/otelcollector/config/metric/agent/config_builder.go
internal/otelcollector/config/metric/agent/config_builder_test.go
internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
internal/otelcollector/config/metric/gateway/config_builder.go
internal/otelcollector/config/metric/gateway/config_builder_test.go
internal/otelcollector/config/trace/gateway/config_builder.go
internal/otelcollector/config/trace/gateway/config_builder_test.go

In order to seacrh and read the logs in a connected log backend, it will be beneficial that the otel components log in JSON output.
- Enable JSON based log output for all otel-collector instances
Closes:

feat: OTel-collector logs in JSON encoding only

---

internal/kubernetes/owner_reference_setter.go
internal/kubernetes/owner_reference_setter_test.go
internal/reconciler/logpipeline/reconciler.go
internal/reconciler/metricpipeline/reconciler.go
internal/reconciler/tracepipeline/reconciler.go

- [The newest controller-runtime version](https://github.com/kyma-project/telemetry-manager/pull/319) introduces a feature called client interceptors. These interceptors provide a way to execute additional actions during client operations. This pull request leverages this new functionality to streamline and simplify the code for setting owner references, eliminating the need for repetitive code blocks.
Irrelevant
Irrelevant

chore: Owner reference interceptor

---

Makefile
config/manager/kustomization.yaml
module_config.yaml
sec-scanners-config.yaml

- Bump images and module version in preparation for 1.1.0 release
Closes:

chore: Bump images and module version for 1.1.0 release

---

docs/contributor/performance-tests/metrics/metrics.md
internal/otelcollector/config/exporters.go
internal/otelcollector/config/metric/gateway/config.go
internal/otelcollector/config/metric/gateway/config_builder.go
internal/otelcollector/config/metric/gateway/config_builder_test.go
internal/otelcollector/config/trace/gateway/config.go
internal/otelcollector/config/trace/gateway/config_builder.go
internal/otelcollector/config/trace/gateway/config_builder_test.go
main.go
sec-scanners-config.yaml
test/testkit/mocks/backend/config_map.go
test/testkit/mocks/backend/deployment.go

- remove loggingexporter usage
- use newest image having loggingexporter replaced by debugexporter
Closes: 
https://github.com/kyma-project/telemetry-manager/issues/440
https://github.com/kyma-project/third-party-images/pull/387

feat: Remove loggingexporter from gateways

---

docs/user/04-metrics.md

- Update metric agent KPIs and limitations
Closes:

docs: Update metric pipeline KPIs

---

docs/user/03-traces.md

- added new symptom for trace troubleshooting
Closes:

docs: Added new trace troubleshooting symptom

---

apis/operator/v1alpha1/telemetry_types.go
config/crd/bases/operator.kyma-project.io_telemetries.yaml
docs/user/resources/01-telemetry.md
test/e2e/metrics_basic_test.go
test/e2e/traces_basic_test.go

- Improved API description for manual scaling
- Added minimum constraint
Closes:
https://github.com/kyma-project/telemetry-manager/issues/430

feat: Constraint minimal replicas

---

docs/contributor/performance-tests/metrics/metrics.md
docs/user/04-metrics.md
internal/otelcollector/config/metric/gateway/config_builder_test.go
internal/otelcollector/config/metric/gateway/processors.go
internal/otelcollector/config/metric/gateway/processors_test.go
internal/resources/otelcollector/agent/resources.go

- Add hardened metric gateway memory_limiter configuration
- Enable metric gateway load balancing from metric agent, added annotation `traffic.sidecar.istio.io/includeOutboundPorts` to metric agent for port 4317
- Add metric gateway/CLS  performance and throughput test documentation
- Add metric gateway throughput and limitation documentation for end user
Closes:

feat: Add metric gateway hardened configuration

---

config/busola/logpipeline_busola_extension_cm.yaml
webhook/logpipeline/webhook.go

- Added missing mTLS sections to LogPipeline view
- Fixed broken LogPipeline edit view by removing namespace selector for now
- Fixed inline docu link
Closes:

feat: TLS settings in LogPipeline view

---

internal/reconciler/logpipeline/reconciler.go
internal/reconciler/logpipeline/sync.go
internal/reconciler/logpipeline/sync_test.go

- The secret changes should be synced only deployable pipelines.
Closes:
https://github.com/kyma-project/telemetry-manager/issues/485

fix: Sync secrets for deployable pipelines only.

---

Makefile
config/manager/kustomization.yaml
module-config-dev.yaml
module-config.yaml
sec-scanners-config.yaml

- Bump images and module version in preparation for releasing version 1.2.0
Closes:

chore: Bump images and module version for 1.2.0 release

---

Makefile

- Bumps istio module dep to 1.1.1
Closes:

deps: Bump istio module dependency to 1.1.1

---

test/e2e/traces_noisy_span_filter_test.go
test/testkit/kyma/common_names.go
test/testkit/otlp/traces/helpers.go
test/testkit/verifiers/traces.go

- Fix and simplify the verifier to only check for trace id
- Add unused test
Closes:

test: Fix noisy span filter E2E tests

---

.github/workflows/pull-governance.yml

- Bump amannn/action-semantic-pull-request to 5.3.0
Closes:
See also https://github.com/kyma-project/community/pull/855

chore: Bump amannn/action-semantic-pull-request to 5.3.0

---

.github/workflows/pull-module.yml
.github/workflows/push-integration.yml
.github/workflows/slack-message.json
Makefile
hack/deploy-module.sh

- fix slack notification
- move module verification job to GH actions
Closes:

chore: Add missing github actions

---

.github/workflows/slack-message.json

- Try to fix the slack notification used in pull-based jobs
- Switched message payload to use only github context variables
Closes:

fix: Adjust slack notifier payload in github action

---

config/samples/telemetry_v1alpha1_metricpipeline.yaml

- Fix the port names in the service for the metric pipeline example
Closes:

fix: The metric pipeline example

---

config/samples/telemetry_v1alpha1_metricpipeline.yaml

- Use OTLP endpoint for metric pipeline
Closes:

fix: Incorrect indentation of metric pipeline

---

Makefile
config/manager/kustomization.yaml
module-config-dev.yaml
module-config.yaml
sec-scanners-config.yaml

- Bump images and module version in preparation for releasing version 1.3.0
Closes:

chore: Bump images and module version for 1.3.0 release

---

Makefile

- fix release script by passing the GORELEASER_VERSION env variable
Closes:

chore: Pass GORELEASER_VERSION env variable to release script

---

Makefile

- Cherry-pick the fix for the release script https://github.com/kyma-project/telemetry-manager/pull/518
Closes:

chore: Cherry-pick the fix for the release script

---

hack/deploy-module.sh
hack/release.sh

- Use the `--module-archive-version-overwrite` flag when creating module with Kyma CLI. This flag is needed to overwrite an exiting module image with the same version. This is needed for example for the release job if the first release job execution is failed, but the module image is already pushed, then in the second attempt of release job execution, we need to overwrite the image.
Closes:

chore: Use --module-archive-version-overwrite flag when creating module

---

hack/deploy-module.sh
hack/release.sh

- Cherry-pick the usage of `--module-archive-version-overwrite` flag https://github.com/kyma-project/telemetry-manager/pull/520
Closes:

chore: Cherry-pick the usage of --module-archive-version-overwrite flag

---

.github/workflows/pull-code-checks.yml

- Configure link checker to not validate against main branch
- Changes inspired by https://github.com/kyma-project/kyma/pull/18322/files
Closes:

chore: Configure link checker to not validate against main branch

---

main.go
sec-scanners-config.yaml

- Bump directory-size-exporter to update Golang to 1.21.4
Closes:
Related issues: https://github.com/kyma-project/directory-size-exporter/pull/34

chore: Bump directory-size-exporter to update Golang

---

docs/user/integration/sap-cloud-logging/README.md

The SAP Cloud Logging Service will be available soon. Here a first draft on how to integrate with it.
- first draft version for a integration guide
Closes:

docs: Add first version of SAP CLS integration

---

docs/contributor/performance-tests/metrics/metrics.md
internal/resources/otelcollector/gateway.go
internal/resources/otelcollector/gateway_test.go

- Remove sessionAffinity from gateway, test, and docs
Closes: Resolves #500 

fix: Remove session affinity for Otel collector services

---

docs/user/integration/sap-cloud-logging/README.md

Changes proposed in this pull request: Improve integration guide for SAP Cloud Logging

docs: Improve integration with sap cloud logging

---

test/testkit/mocks/backend/config_map.go
test/testkit/mocks/logproducer/log_producer.go
test/testkit/periodic/periodic.go

- Optimize log producer to produce less logs
- Reduce log produced by the OTEL mock backend, this logs collected with fluent-bit and pushed back to the OTEL backend (avoid recursive log collection)
Closes:
https://github.com/kyma-project/telemetry-manager/issues/441

fix: Flaky e2e logging test

---

Makefile

- Add e2e logging test to gardener integration test 
Closes:
https://github.com/kyma-project/telemetry-manager/issues/441

test: Enable e2e logging tests for gardener integration test

---

.golangci.yaml
apis/telemetry/v1alpha1/logpipeline_validation.go
main.go

- Enable gocyclo linter
- Refactor functions with the worst cyclomatic complexity
Closes:
Related issues: https://github.com/kyma-project/telemetry-manager/issues/114

test: Enable gocyclo linter

---

docs/user/03-traces.md
docs/user/integration/sap-cloud-logging/README.md

- Fix broken links after moving the `Istio access logs` tutorial to the `istio` repo
Related PR: https://github.com/kyma-project/kyma/pull/18421

docs: Fix broken links

---

Makefile
config/manager/kustomization.yaml
module-config-dev.yaml
module-config.yaml
sec-scanners-config.yaml

- Prepare version 1.4.0
Closes:

chore: Bump images and module version for 1.4.0 release

---

Makefile

- Add gardener GCP machine type parameter to gardener integration test target
Closes:
https://github.com/kyma-project/telemetry-manager/issues/441

test: Change Gardener GCP machine type for gardener integration test

---

docs/user/integration/sap-cloud-logging/README.md

- enhanced the prerequisite section
Closes:

docs: Enhance prerequisites in Cloud Logging integration tutorial

---

sec-scanners-config.yaml

- Update to Otel Collector 0.89.0
Closes:
Related issues: https://github.com/kyma-project/third-party-images/pull/400

feat: Update to Otel Collector 0.89.0

---

Makefile

- Update Istio module version to 1.1.2 for tests
Closes:

test: Update Istio module version for integration tests

---

.github/workflows/pull-module.yml
main.go
sec-scanners-config.yaml
test/testkit/mocks/backend/deployment.go

Currently the otel-collector is based on a distroless image bringing unneeded dependencies like OpenSSL. It will be much better from maintenance perspective to make it based on a scratch image.
- Update to scratch based image of otel-collector
Closes:
https://github.com/kyma-project/third-party-images/pull/402

chore: Update to scratch based image of otel-collector

---

test/integration/istio/metrics_otlp_input_test.go

- The flakiness was caused by reusing the same backend namespace in 2 separate test cases
Changes refer to particular Issues, PRsor Documents:
-

test: Fix flaky Istio test

---

.github/pull-request-template.md
Makefile

- Update to istio module 1.2.0
- Fixed spelling in PR template
Changes refer to a particular Issues, PRs or Documents:
-

chore: Update to istio module 1.2.0

---

test/integration/istio/metrics_otlp_input_test.go

-  Improve the istio tests for push metrics. Introduce 2 deployments with and without side-car and these would push metrics to the metrics gateway
- Also use telemetry-gen to produce metrics
- https://github.com/kyma-project/telemetry-manager/pull/568

test: Improve push metrics test

---

internal/otelcollector/ports/ports.go
internal/reconciler/metricpipeline/reconciler.go
internal/reconciler/tracepipeline/reconciler.go
internal/resources/otelcollector/agent.go
internal/resources/otelcollector/agent_test.go
internal/resources/otelcollector/config.go
internal/resources/otelcollector/core.go
internal/resources/otelcollector/gateway.go
internal/resources/otelcollector/gateway_test.go
test/e2e/metrics_basic_test.go
test/e2e/traces_basic_test.go
test/integration/istio/metrics_otlp_input_test.go
test/integration/istio/traces_test.go
test/testkit/k8s/network_policy.go

- cherry-picked following PR: https://github.com/kyma-project/telemetry-manager/pull/627 
-

fix: Allow network policy based on signal type (#627)

---

docs/user/README.md
docs/user/gateways.md

- Adds new section about default resource usage of the module
- -

docs: Add minimal resource usage

---

Makefile
config/manager/kustomization.yaml
main.go
module-config.yaml
sec-scanners-config.yaml

- Bump the operator image
- Bump Fluent Bit exporter
- Bump module version

chore: Bump images and module version 1.6.0

---

internal/reconciler/telemetry/status.go
internal/reconciler/telemetry/status_test.go

- Cheery-pick https://github.com/kyma-project/telemetry-manager/pull/669
-

fix: Metric gateway endpoint not set in module status (#669)

---

controllers/operator/telemetry_controller_test.go

- Add integration test, test MetricPipeline and TracePipeline gateway endpoint in the module status
- https://github.com/kyma-project/telemetry-manager/pull/669

test: Add Telemetry Module integration test for metric and trace gateway endpoints in status

---

Makefile

- Bump Istio module to 1.2.1 for integration tests
-

test: Bump Istio module for integration tests

---

docs/user/resources/01-telemetry.md
docs/user/resources/05-metricpipeline.md

- User docs updated with new MetricPipeline status 
-

fix: Update user docs with new MetricPipeline status

---

docs/user/03-traces.md
docs/user/04-metrics.md

- Fixed intendation in istio tracing example
- Fixed a small mistake talking about `input.application` atttribute in metrics docu
-

docs: Fixed intendation in istio tracing example

---

docs/user/integration/jaeger/README.md
docs/user/integration/loki/README.md
docs/user/integration/opentelemetry-demo/README.md

- fixed broken values.yaml links
- Improved the explanatory sentence around the custom values.yaml
-

docs: Fix broken values.yaml links

---

docs/user/integration/dynatrace/README.md
docs/user/integration/dynatrace/secret-example.yaml

- Improve the documentation for dynatrace
-

docs: Improve dynatrace documentation

---

.testcoverage.yml
internal/resources/otelcollector/config_test.go

- Increase test coverage for `internal/resources/otelcollector` package
-

test: Increase test coverage for "internal/resources/otelcollector" pkg

---

docs/contributor/governance.md

- Updated two more links to a GitHub Action
-

docs: Update links

---

docs/user/integration/loki/README.md

Replace html tags with docsify toggles because of https://github.com/kyma-project/kyma/issues/18379
- https://github.com/kyma-project/kyma/issues/18379

docs: Replace html tags with docsify toggles

---

Makefile

- Bump istio module to 1.3.0
-

chore: Bump istio module to 1.3.0

---

docs/user/01-manager.md
docs/user/README.md

- the future is NOW
- only one guide
-

docs: Fix minor errors

---

docs/user/integration/aws-cloudwatch/README.md

- Fixed a section link detected by the Markdown Link Check
- `docs/user/integration/aws-cloudwatch/README.md`

docs: Fix a link

---

.github/workflows/pr-docu-checks.yml

Switch to md-check-link
- Use [md-check-link](https://github.com/kyma-project/md-check-link/) that supports docsify and anchors properly

chore: Update pr-docu-checks.yml

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump operator image in preparation for releasing module version 1.9.0
-

chore: Bump operator image for 1.9.0 release

---

config/samples/http-mockserver.yaml
main.go
sec-scanners-config.yaml

- Update Fluent-Bit image version to 2.2.2
- https://github.com/kyma-project/telemetry-manager/issues/765

feat: Update Fluent-Bit image version to 2.2.2

---

Makefile

- Bump Istio module to 1.3.1 for integration tests
-

chore: Bump Istio module to 1.3.1 for integration tests

---

docs/contributor/pocs/performance-tests/metrics/metrics.md
docs/user/integration/dynatrace/README.md
docs/user/integration/opentelemetry-demo/README.md

- we had inconsistent prepositions, this should fix it.
- https://github.com/kyma-project/kyma/issues/18581

docs: Say IN a cluster not ON a cluster

---

docs/user/integration/sap-cloud-logging/README.md

- make documentation more clear
- SAP internal bug tickets

docs: Highlight the need for Istio configuration to get access logs

---

docs/user/02-logs.md
docs/user/03-traces.md
docs/user/04-metrics.md

- fix table rendering
- just a small fix
Related to https://github.com/orgs/kyma-project/projects/18/views/5?pane=issue&itemId=54729957

docs: Add an empty line before tables

---

.github/workflows/pr-lifecycle.yml

fix: Change manager deployment name in upgrade test

---

controllers/telemetry/logpipeline_controller_test.go
internal/fluentbit/config/builder/config_builder_test.go
internal/fluentbit/config/builder/kubernetes_filter.go
internal/fluentbit/config/builder/kubernetes_filter_test.go
webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf

- Backport https://github.com/kyma-project/telemetry-manager/pull/835
- https://github.com/kyma-project/telemetry-manager/issues/834

fix: Increase Fluent Bit Kubernetes filter buffer

---

.github/template/setup-golang/action.yaml
.github/workflows/pr-code-checks.yml

- Update GH action versions were possible
- golangci-lint-action
- setup-go
-

chore: Update gh action version

---

Makefile

- Update tests to use istio module 1.3.2
-

chore: Update tests to istio 1.3.2

---

Makefile
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump images to prepare release 1.10.1
-

chore: Prepare release 1.10.1

---

docs/contributor/arch/006-telemetry-api-v1beta1.md

fix: Broken indentation in list

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump Telemetry Manager image in preparation for releasing module version 1.11.0
-

chore: Bump images for 1.11 release

---

docs/contributor/releasing.md

- remove list with just a single item
-

fix: Remove unnecessary list

---

.github/workflows/tag-release.yml

- Fix release GitHub action by introducing a step to install kustomize
-

chore: Fix release GitHub action

---

.github/workflows/pr-loadtest.yml
hack/deploy-telemetry.sh

- Create the `kyma-system` namespace if it does not exist
- Execute cluster deletion always
-

chore: Fix the load test action

---

.github/workflows/pr-loadtest.yml

-  Deprovisioning of the cluster needs Service Account so set it as well as env variable
-

chore: Fix the deprovisioning

---

docs/user/integration/dynatrace/README.md

- Added a missing header prefix 
-

docs: Fix Dynatrace integration guide

---

internal/conditions/conditions.go
internal/conditions/conditions_test.go
internal/reconciler/logparser/status.go
internal/reconciler/logparser/status_test.go
internal/reconciler/logpipeline/status.go
internal/reconciler/logpipeline/status_test.go
internal/reconciler/tracepipeline/status.go
internal/reconciler/tracepipeline/status_test.go
test/testkit/verifiers/logs.go
test/testkit/verifiers/traces.go

- Cheery-pick https://github.com/kyma-project/telemetry-manager/pull/887 for release 1.11.1
-

fix: Ensure pending condition is always preserved

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

chore: Prepare release 1.11.1

---

docs/contributor/pocs/otlp-logs.md

- Add documentation about access logs PoC
- #821

docs: Add documentation about access logs PoC

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Bump image version to 1.12.0
-

chore: Prepare release 1.12.0

---

docs/user/gateways.md

Doc adjustment according to the [guideline](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/03-formatting.md#ordered-and-unordered-lists) 
> use lists to create visual clarity within your content. List items in a category or in a sequence. Use an ordered list for sequential, instructional steps. Unordered lists are appropriate for items that have no sequential order, such as a list of valid file types. Follow these guidelines:

docs: Fix unordered lists

---

test/e2e/telemetry_logs_analysis_test.go
test/integration/istio/metrics_otlp_input_test.go
test/testkit/mocks/servicenamebundle/service_name_bundle.go
test/testkit/mocks/telemetrygen/telemetrygen.go

- Extend the testkit to be able to inject resource and telemetry attributes
- Bump telemetrygen version
-

chore: Extend telemetrygen pkg

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

- bump .env file
- bump sec-scanner-config file
-  bump kustomization.yaml
-

chore: Prepare release 1.13.0

---

docs/user/02-logs.md
docs/user/resources/02-logpipeline.md
docs/user/resources/04-tracepipeline.md
docs/user/resources/05-metricpipeline.md

- Add pipeline health condition docs for LogPipeline, TracePipeline, and MetricPipeline
- #917, #918

docs: Add pipeline health condition docs

---

internal/otelcollector/config/config.go
internal/otelcollector/config/metric/agent/config_builder.go
internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
internal/otelcollector/config/metric/gateway/config_builder.go
internal/otelcollector/config/trace/gateway/config_builder.go

- Enable pprof for metric agent
- Extact common logic for OTel Collectors
-

feat: Enable pprof for metric agent

---

internal/otelcollector/config/config.go
internal/otelcollector/config/metric/agent/config_builder.go
internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
internal/otelcollector/config/metric/gateway/config_builder.go
internal/otelcollector/config/trace/gateway/config_builder.go

feat: Enable pprof for metric agent (#981) [Backport for 1.13]

---

.github/template/setup-golang/action.yaml

- use the go version specified in go.mod in GHActions
-

chore: Use go.mod in actions

---

docs/user/03-traces.md
docs/user/04-metrics.md

- I may or may not have found copy/paste errors in our docs, pls check: Do we really want to talk about logs here?

docs: Fix inconsistencies

---

docs/user/integration/dynatrace/README.md

- Fixed the yaml format of the dynakube example snippet
-

docs: Fix dynatrace integration example snippet

---

controllers/operator/telemetry_controller_test.go
internal/otelcollector/config/metric/agent/config_builder_test.go
internal/otelcollector/config/metric/agent/processors_test.go
internal/otelcollector/config/metric/agent/receivers_test.go
internal/otelcollector/config/metric/gateway/config_builder_test.go
internal/otelcollector/config/metric/gateway/processors_test.go
internal/otelcollector/config/trace/gateway/config_builder_test.go
internal/reconciler/logpipeline/reconciler_test.go
internal/reconciler/logpipeline/status_test.go
internal/reconciler/metricpipeline/status_test.go
internal/reconciler/tracepipeline/status_test.go
internal/testutils/log_pipeline_builder.go
internal/testutils/metric_pipeline_builder.go
internal/testutils/pipeline_opts.go
internal/testutils/pipline_opts.go
internal/testutils/trace_pipeline_builder.go

- The status file for different pipelines does not have unit test coverage for tlsCertificate verification add the tests to improve the coverage
-

test: Improve unit test coverage for status

---

internal/reconciler/telemetry/reconciler.go

- Remove orphaned Network Policies cleanup logic
- Resolves #739

chore: Remove orphaned Network Policies cleanup

---

config/busola/telemetry_busola_extension_cm.yaml

- Enhance dashboard extension to configure and show metrics gateway replicas
- Rename "Trace" to "Tracing" in dashboard
-

feat: Add support to configure metric gateway replicas in Kyma Dashboard

---

config/busola/telemetry_busola_extension_cm.yaml

- Rename tracing to traces in dashboard extension
- https://github.com/kyma-project/telemetry-manager/pull/1042#discussion_r1593524480

chore: Rename tracing to traces in dashboard extension

---

apis/operator/v1alpha1/telemetry_types.go
apis/telemetry/v1alpha1/logparser_types.go
apis/telemetry/v1alpha1/logpipeline_types.go
apis/telemetry/v1alpha1/metricpipeline_types.go
apis/telemetry/v1alpha1/tracepipeline_types.go
apis/telemetry/v1beta1/logpipeline_types.go
apis/telemetry/v1beta1/metricpipeline_types.go
apis/telemetry/v1beta1/tracepipeline_types.go
hack/make/dependencies.mk
main.go
test/testkit/mocks/loggen/log_producer.go

- Fix lint violation
- Always pull the latest version of `golangci-lint` when executing `make lint`
-

chore: Fix lint

---

hack/make/provision.mk

- In case multiple supported OS or K8s versions are available, just break the loop after the first one is found
-

chore: Fix gardener provisioning script

---

.github/workflows/pr-integration.yml
test/e2e/logs_multi_pipeline_max_pipeline_test.go
test/e2e/logs_webhook_test.go
test/e2e/metrics_multi_pipeline_max_pipeline_test.go
test/e2e/traces_multi_pipeline_max_pileline_test.go
test/testkit/suite/suite.go

- Fix flaky e2e test
- Run max pipeline e2e test in an isolated environment to reduce influence from other tests
-

test: Fix flaky e2e test, test max pipelines in an isolated environment

---

docs/contributor/releasing.md

- Clarify a (potentially ambiguous) requirement in the release process documentation.
-

docs: Update release process documentation

---

docs/user/integration/loki/README.md

- The current warning talks about additional charging for commercial usage. Usage in commercial context is indeed fine, but you might need to open source your project as well. To not give wrong hints, I tried to formulize the warning better
-

docs: Improve license warning for loki integration guide

---

Dockerfile

- Update telemetry-manager to latest fluent-bit version 3.0.3
- https://github.com/kyma-project/telemetry-manager/pull/1027

fix: Update telemetry-manager to latest fluent-bit version 3.0.3

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

chore: Bump telemetry-manager image to 1.16.0

---

hack/make/provision.mk

- Fix rendering Gardener shoot spec in Makefile
- https://github.com/kyma-project/telemetry-manager/actions/runs/9186514208/job/25262334796
- https://github.com/kyma-project/telemetry-manager/pull/1083
- https://github.com/kyma-project/kyma/issues/18674

chore: Fix rendering Gardener shoot spec

---

docs/contributor/arch/012-leader-receiver-creator.md

-  Leader Receiver Creator ADR
- https://github.com/kyma-project/telemetry-manager/issues/1003

docs: Leader Receiver Creator ADR

---

.github/pull-request-template.md

- Update pull-request-template
-

docs: Update pull-request-template.md

---

docs/user/integration/dynatrace/README.md

docs: Fix example in the Dynatrace guide

---

docs/contributor/releasing.md
internal/otelcollector/config/metric/agent/config_builder.go
internal/otelcollector/config/metric/agent/config_builder_test.go
internal/otelcollector/config/metric/agent/processors.go
internal/otelcollector/config/metric/agent/processors_test.go
internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
internal/otelcollector/config/metric/agent/set_instrumention_scope.go
internal/reconciler/metricpipeline/reconciler.go
internal/version/version.go
main.go

- Fix instrumentation scope unit tests on release branches
- #1000

test: Fix instrumentation scope unit tests on release branches

---

config/busola/telemetry_busola_extension_cm.yaml

- Revert of https://github.com/kyma-project/telemetry-manager/pull/1092
- Relates to https://github.com/kyma-project/istio/pull/856

fix: Change UI path for telemetry CR back

---

docs/user/integration/dynatrace/README.md

- fixes intendation problems
-

docs: Fix intendation problems in dynatrace guide

---

config/busola/telemetry_busola_extension_cm.yaml

- Backport https://github.com/kyma-project/telemetry-manager/pull/1140
- https://github.com/kyma-project/telemetry-manager/pull/1140

fix: Change UI path for telemetry CR back (#1140)

---

.github/workflows/pr-loadtest.yml

- Refactored the matrix arguments to be structured and enriched them with the related image name
- Added new input for image to test
- Runs a matrix job only if the image fits
-

chore: Run perf tests only for specific images

---

.github/workflows/pr-loadtest.yml

- Fixed skip logic in perf test
-

chore: Fixed skip logic in perf test

---

.env
config/manager/kustomization.yaml
sec-scanners-config.yaml

- Update images for telemetry-manager 1.6.2
-

chore: Update images for telemetry-manager 1.6.2

---

.env
config/manager/kustomization.yaml
internal/otelcollector/config/metric/agent/processors_test.go
internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
internal/version/version.go
sec-scanners-config.yaml

- Update images for telemetry-manager 1.17.1
-

chore: Update images for telemetry-manager 1.17.1

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- Bump images for 1.18.0 release
-

chore: Bump images for 1.18.0 release

---

Dockerfile
go.mod

deps: Update golang to 1.22.4

---

.github/workflows/pr-loadtest.yml

- upload loadtest results as test artifacts
-

chore: Upload loadtest results as artifacts

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- bump .env file
- bump sec-scanner-config file
- bump kustomization.yaml
-

chore: Prepare release 1.19

---

sec-scanners-config.yaml

-  Bump directory exporter image to latest
-

chore: Bump directory exporter image

---

hack/make/provision.mk
hack/shoot_gcp.yaml

- fix gardener cron expression
-

fix: Gardener cluster setup

---

.github/workflows/pr-github-checks.yml

- check for required labels `kind` and `area`
- check that `kind` matches PR title prefix
-

chore: Validate PR labels

---

hack/make/provision.mk

- debug print environment
- proper use of variables in makefile
-

chore: Add printout for environment

---

internal/tlscert/tls_cert_validator.go

- Refactor TLS validator code and logic
- Improves https://github.com/kyma-project/telemetry-manager/pull/1215

chore: Refactor TLS validator logic

---

Dockerfile
go.mod
internal/tools/go.mod

chore: Update to golang 1.22.5

---

.github/workflows/pr-github-checks.yml

- Update label prefix mapping
-

chore: Update label prefix mapping

---

internal/reconciler/logparser/reconciler.go
internal/reconciler/logpipeline/reconciler.go
internal/reconciler/tracepipeline/reconciler.go

- Remove throw-away migration code
- https://github.com/kyma-project/telemetry-manager/issues/1206

chore: Remove legacy pipeline cleanup

---

.github/workflows/pr-github-checks.yml

- check if a milestone is set on the PR
-

chore: Check if milestone is set

---

.golangci.yaml
docs/contributor/pocs/otlp-logs.md
docs/user/03-traces.md
docs/user/integration/dynatrace/README.md
docs/user/integration/jaeger/README.md
docs/user/integration/opentelemetry-demo/README.md
docs/user/integration/sap-cloud-logging/README.md
hack/deploy-istio.sh
hack/load-tests/log-fluentbit-backpressure-config.yaml
hack/load-tests/metric-agent-backpressure-config.yaml
hack/load-tests/metric-backpressure-config.yaml
hack/load-tests/self-monitor-test-setup.yaml
hack/load-tests/trace-backpressure-config.yaml
internal/k8sutils/utils.go
internal/resources/otelcollector/gateway.go
internal/resources/otelcollector/gateway_test.go
main.go
test/integration/istio/suite_test.go
test/testkit/k8s/peer_authentication.go
test/testkit/k8s/virtual_service.go

- Update manager to use new Istio versions for peerauthentication
- Updated yaml snippets in tests to use new versions
- Updated tests to use telemetry v1 resources
- Updated docu to use new versions
- Removed alpha disclaimer from docu
-

feat: Switch to Istio stable APIs

---

.github/pull-request-template.md

- remove milestone checkbox from PR template
-

chore: Update pr-template

---

test/e2e/telemetry_logs_analysis_test.go

- ENVvar expansion is was excluded from our deprecation check
-

chore: Remove test exclusion for ENVvar expansion

---

docs/contributor/releasing.md

- update releasing.md to include information about the OCC repository
-

chore: Include information about OCC repository in release process

---

test/testkit/assert/logs.go
test/testkit/assert/metrics.go
test/testkit/assert/traces.go

- A further improvement of https://github.com/kyma-project/telemetry-manager/pull/1266
- #1253

chore: Improve pipeline healthiness assertions in e2e testkit

---

controllers/telemetry/tracepipeline_controller.go
internal/reconciler/tracepipeline/reconciler.go
internal/reconciler/tracepipeline/reconciler_test.go
internal/reconciler/tracepipeline/status.go
main.go

- Second part of https://github.com/kyma-project/telemetry-manager/pull/1269
-

chore: Refactor dependency management in TracePipeline reconciler

---

controllers/telemetry/metricpipeline_controller.go
internal/reconciler/metricpipeline/reconciler.go
internal/reconciler/metricpipeline/reconciler_test.go
main.go

- Second part of https://github.com/kyma-project/telemetry-manager/pull/1269
-

chore: Refactor dependency management in MetricPipeline reconciler

---

.github/workflows/pr-loadtest.yml

- change the run-name for load tests
-

chore: Print meaningful runname for load tests

---

docs/user/integration/aws-cloudwatch/README.md
docs/user/integration/dynatrace/README.md
docs/user/integration/jaeger/README.md
docs/user/integration/loki/README.md
docs/user/integration/opentelemetry-demo/README.md

docs: Change enable and disable to add and delete in the telemetry repo

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- Bump images for 1.21.0 release
-

chore: Bump images for 1.21.0 release

---

docs/user/02-logs.md
docs/user/03-traces.md
docs/user/04-metrics.md
docs/user/integration/sap-cloud-logging/README.md

- apply @grego952 's suggestions from Help Portal review
-

docs: Implement TW Review

---

docs/contributor/releasing.md

- Update releasing docs since we moved from prow to GH actions
-

chore: Update docs to correspond to new release workflow

---

.github/workflows/build-image.yml
.github/workflows/pr-code-checks.yml
.github/workflows/pr-docu-checks.yml
.github/workflows/pr-github-checks.yml
.github/workflows/pr-integration.yml
.github/workflows/pr-lifecycle.yml

- repository rules need checks. To not have to enter each job as a check this PR introduces a single job per workflow that relies on all other jobs. It can then be used as a check
-

chore: Prepare checks for repo rule

---

.github/workflows/pr-github-checks.yml

- Add a new GHA that prevents modifying `kustomization.yaml`
-

chore: Implement pr-prevent-kustomization GHA

---

.github/workflows/pr-code-checks.yml
.github/workflows/pr-skip-on-docu-paths.yml
.github/workflows/skip-on-docu-paths.yml

- Fix broken workflow
- https://github.com/kyma-project/telemetry-manager/pull/1376

chore: Fix gha workflow

---

.github/workflows/pr-code-checks.yml

chore: Replace workflow path filter with changed-files

---

.github/workflows/pr-code-checks.yml
.github/workflows/pr-integration.yml
.github/workflows/pr-lifecycle.yml

- Replaced workflow path filter with changed-files
- https://github.com/kyma-project/telemetry-manager/pull/1382

chore: Replace workflow path filter with changed-files (pt. 2)

---

.github/workflows/pr-lifecycle.yml

- Only run upgrade tests if a source file is changed
- https://github.com/kyma-project/telemetry-manager/pull/1382
- https://github.com/kyma-project/telemetry-manager/pull/1383

chore: Only run upgrade tests if a source file is changed

---

.github/workflows/pr-github-checks.yml

- cherry-picked from main: https://github.com/kyma-project/telemetry-manager/pull/1393
-

chore: Revert "chore: Implement pr-prevent-kustomization GHA"

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- Bump the images for release 1.22.0
- update sec-scanner-config.yaml and main.go
-

chore: Prepare release 1.22.0

---

docs/user/integration/sap-cloud-logging/README.md

- Fix example code indentation
-

docs: Fix some code indentation

---

CONTRIBUTING.md

- Update CONTRIBUTING.md
- https://github.com/kyma-project/community/issues/926

docs: Update the contributing file

---

internal/reconciler/telemetry/reconciler.go

- Unify the Telemetry reconciler with the change made in https://github.com/kyma-project/telemetry-manager/pull/1430
-

chore: Unify Telemetry status reconciliation with the rest of reconcilers

---

.github/workflows/build-image.yml
hack/await_workflow.sh

- Reduce poll frequency to check every 30 seconds
- Remove "edited" activity type trigger from build image workflow
- Silence curl progress bar
- Add HTML_URL for better debugging
-

chore: Improve await_workflow script output

---

docs/user/integration/dynatrace/README.md

- With dynatrace-operator 1.2.x the namespaceSelector just moved, so I adjusted the snippet
-

docs: Fixed namespaceSelector for dynatrace tutorial

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- Bump images for 1.24.0 release
-

chore: Bump images for 1.24.0 release

---

config/busola/metricpipeline_busola_extension_cm.yaml

- Add Node metrics selector to the UI (Busola)
- #1300

feat: Add Node metrics selector to the UI

---

internal/otelcollector/config/metric/gateway/processors.go
internal/otelcollector/config/metric/gateway/processors_test.go
internal/otelcollector/config/ottlexpr/expressions.go

- The filter expression was hard to read and unsafe regarding the priority on "and" and "or"
- The expression used many IsMatch expressions which requires regexp evaluation many times
- The new expression applies only one regexp and should have a better performance
-

chore: Simplified filter expression

---

docs/contributor/arch/015-impact-of-istio-prometheus-merge-on-metric-pipelines.md

- Update ADR
- https://github.com/kyma-project/telemetry-manager/issues/1468

docs: Update Istio metric merge ADR

---

.env
config/manager/kustomization.yaml
docs/user/03-traces.md
docs/user/integration/sap-cloud-logging/README.md
main.go
sec-scanners-config.yaml

- Bump images to include the leader election fix: https://github.com/kyma-project/opentelemetry-collector-components/pull/149
- Cherry-pick broken links fix to make the markdown linter happy: https://github.com/kyma-project/telemetry-manager/pull/1582
-

chore: Prepare images for 1.26.2 release

---

.env
config/manager/kustomization.yaml
main.go
sec-scanners-config.yaml

- Bump images for 1.27.0 release
-

chore: Bump images for 1.27.0 release

---

.github/workflows/pr-integration.yml

chore: Change image based on event

---

.github/workflows/pr-lifecycle.yml

chore: Fix lifecyle tests with merge_group trigger

---

.env

- Fix a mistake made in https://github.com/kyma-project/telemetry-manager/pull/1688
-

chore: Fix operator image tag

---

docs/user/integration/sample-app/go.mod
docs/user/integration/sample-app/go.sum

- Tests the build workflow for the new sample-app, see https://github.com/kyma-project/telemetry-manager/pull/1733
-

test: check image build for sample app

---

internal/tools/populateimages/main.go
sec-scanners-config.yaml

- Linked PR changed the naming of the security scanner settings, fixing it
- https://github.com/kyma-project/telemetry-manager/pull/1671

chore: Fix security scanner setup

---

external-images.yaml

- Update fluentbit image to 3.2.4, PR bumping the actual image will follow
-

chore: Update fluentbit image to 3.2.4

---

.env
config/manager/kustomization.yaml
internal/images/images.go
main.go
sec-scanners-config.yaml

- Prepare images for 1.33.0 release
-

chore: Prepare images for 1.33.0 release

---

.github/workflows/pr-github-checks.yml

chore: fix milestone automation and remove project automation

---

.github/workflows/pr-github-checks.yml

chore: use GH_REPO for milestone action

---

renovate.json

chore: enable gha update

---

go.mod
go.sum

chore: Bump x/oauth2 dependency

---

.env
config/manager/kustomization.yaml
internal/images/images.go
main.go
sec-scanners-config.yaml

- Prepare images for release 1.35
-

chore: prepare release-1.35

---

.github/workflows/tag-release.yml

chore: add permissions to create a release

---

.github/workflows/tag-release.yml

chore: add permissions to create a release (#1895)

---

docs/user/resources/01-telemetry.md

- rephrased section about backward compatibility annotation
- https://github.com/kyma-project/telemetry-manager/pull/1893/files
instead of https://github.com/kyma-project/telemetry-manager/pull/1893/files

docs: Rephrase backward compatibility annotation

---

docs/user/assets/gateways-plain.drawio.svg
docs/user/gateways.md

- a link was broken
- minor adjustments
- https://github.com/kyma-project/telemetry-manager/pull/1930

docs: Edit gateway doc

---

.github/workflows/pr-github-checks.yml

- Revert a change done in https://github.com/kyma-project/telemetry-manager/pull/1955
- Add a custom error message
-

chore(ci): require no scope

---

.env
docs/contributor/benchmarks/README.md
internal/images/images.go
sec-scanners-config.yaml

- update to fluentbit 3.2.10
- update directory-size-exporter
- run benchmark tests
- https://github.com/kyma-project/telemetry-manager/pull/1991
- https://github.com/kyma-project/telemetry-manager/actions/runs/14110261646

feat: update to fluentbit 3.2.10

---

docs/user/04-metrics.md

- align GitHub and Help Portal
- File paths must be code font
- https://github.com/kyma-project/telemetry-manager/pull/1968

docs: align GitHub and Help Portal

---

.github/workflows/branch-integration.yml
.github/workflows/build-image.yml
.github/workflows/slack-message.json

- Upgraded slack GH action to version 2
- Improved payload
-

chore: migrate slack GH action to version 2

---

.github/workflows/branch-integration.yml
.github/workflows/build-image.yml
.github/workflows/pr-all-checks-passed.yml
.github/workflows/pr-github-checks.yml
renovate.json

- update gh action to proper release versions
-

chore: update gh action to proper release versions

---

.env
config/manager/kustomization.yaml
internal/images/images.go
main.go
sec-scanners-config.yaml

- bump images for release 1.38
-

chore: prepare release 1.38

---

.env

- chore: update to newest k3d patch version
- https://github.com/kyma-project/telemetry-manager/pull/2081

chore: update to newest k3d patch version

---

.env
config/manager/kustomization.yaml
internal/images/images.go
main.go
sec-scanners-config.yaml

- https://github.com/kyma-project/opentelemetry-collector-components/milestone/21
-

chore: prepare images for 1.39.0 release

---

.env
internal/images/images.go
sec-scanners-config.yaml

- bump exporter to latest version
-

chore: bump directory-size-exporter

---

docs/user/integration/dynatrace/exporter-values.yaml

- use latest otel-collector version in dynatrace integration guide
- values file is tested continuously in e2e cluster setup
-

docs: use latest otel-collector version in dynatrace integration guide

---

docs/user/integration/dynatrace/README.md

- improved exclude expressions for dynatrace guide
-

docs: improved exclude expressions for dynatrace guide

---

docs/contributor/releasing.md

- update release docs after #1565
-

chore: update release process docs

---

.env
config/manager/kustomization.yaml
internal/images/images.go
sec-scanners-config.yaml

- Bump images for release 1.42.0
-

chore: bump images for 1.42.0 release

---

.env
config/manager/kustomization.yaml
internal/images/images.go
sec-scanners-config.yaml

- Bump images for release 1.43.0
-

chore: bump images to release 1.43.0

---

renovate.json

- group otel packages in renovate
-

chore: group otel packages in renovate

---

.env
config/manager/kustomization.yaml
internal/images/images.go
sec-scanners-config.yaml

- Bump images for 1.44.0 release
-

chore: bump images for 1.44.0 release

---

dependencies/sample-app/main.go

chore: fix the server port

---

.github/workflows/gardener-integration.yml
docs/user/integration/opentelemetry-demo/values.yaml
hack/deploy-istio.sh

- More resilient istio setup in integration test fixes https://github.com/kyma-project/telemetry-manager/actions/runs/16929797856/job/47972520800
- Tell project name in slack notification
- Increase memory limit for otel-demo to not crash in the tests
-

chore: improve several aspects in integration tests

---

renovate.json

chore: include external images in renovate

---

.env
config/manager/kustomization.yaml
config/manager/manager.yaml
sec-scanners-config.yaml
test/testkit/images.go

-  Bump images for release 1.46.0
-

chore: bump images for release 1.46.0

---

docs/user/02-logs.md

- Links got broken by upstream changes, fixed them
-

docs: fix broken fluent bit links

---

external-images.yaml

- update fluentbit image in cache to 4.0.8
-

chore: update fluentbit image in cache to 4.0.8

---

.github/workflows/pr-upgrade.yml
internal/otelcollector/config/common/otlpexporter_config_builders.go
internal/otelcollector/config/common/types.go
internal/otelcollector/config/logagent/config_builder_test.go
internal/otelcollector/config/logagent/testdata/http-protocol-with-custom-path.yaml
internal/otelcollector/config/logagent/testdata/http-protocol-without-custom-path.yaml
internal/otelcollector/config/loggateway/config_builder_test.go
internal/otelcollector/config/loggateway/testdata/http-protocol-with-custom-path.yaml
internal/otelcollector/config/loggateway/testdata/http-protocol-without-custom-path.yaml
internal/otelcollector/config/metricgateway/config_builder_output.go
internal/otelcollector/config/metricgateway/config_builder_test.go
internal/otelcollector/config/metricgateway/testdata/http-protocol-with-custom-path.yaml
internal/otelcollector/config/metricgateway/testdata/http-protocol-without-custom-path.yaml
internal/otelcollector/config/tracegateway/config_builder_test.go
internal/otelcollector/config/tracegateway/testdata/http-protocol-with-custom-path.yaml
internal/otelcollector/config/tracegateway/testdata/http-protocol-without-custom-path.yaml
test/e2e/upgrade/logs_fluentbit_upgrade_test.go
test/e2e/upgrade/logs_upgrade_test.go

- Cherry-pick for the fix from PR https://github.com/kyma-project/telemetry-manager/pull/2471 
- The fix for the upgrade tests had to be also cherry-picked https://github.com/kyma-project/telemetry-manager/pull/2468
- https://github.com/kyma-project/telemetry-manager/issues/2469

fix: fix metric OTLP output with http protocol (#2471)

---

.env
helm/telemetry-module/Chart.yaml
helm/telemetry-module/values.yaml
sec-scanners-config.yaml

-  bump images for 1.47.1 release
-

chore: bump images for 1.47.1 release

---

.env
helm/values.yaml
sec-scanners-config.yaml

- bump directory size-exporter
-

chore: bump directory size-exporter

---

.env
helm/Chart.yaml
helm/charts/default/Chart.yaml
helm/charts/experimental/Chart.yaml
helm/values.yaml
sec-scanners-config.yaml
test/testkit/images.go

Reverts kyma-project/telemetry-manager#2555

chore: revert "chore: bump images for telemetry release 1.49.0"

---

docs/user/integration/opentelemetry-demo/values.yaml

- latest otel-demo version let the flagd component crash, as upstream env variables are not overridable for the "sidecars", so I copy over new env variables for now
- adjusted memory limit for payment component
-

docs: update to latest otel-demo version
